fix: add kenhorlador
EddieHubCommunity/awesome-github-profiles pull request #1003
Opened 2022-02-03 11:58 UTC by kenhorlador

resolve #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-02-03 13:55 UTC, vikasganiga05 requested changes
LGTM :+1: 
But you forgot to link your issue #1002 to this PR.

2022-02-03 14:13 UTC, kenhorlador commented
Done. 

Sorry, I forgot.

2022-02-03 14:56 UTC, schmelto approved these changes

2022-02-03 17:39 UTC, Panquesito7 requested changes

2022-02-03 17:39 UTC, Panquesito7 commented on profiles/kenhorlador.json
> +  "issueId": 1003,
Wrong issue ID.
```suggestion
  "issueId": 1002,
```

2022-02-03 22:07 UTC, schmelto approved these changes

2022-02-04 00:08 UTC, Panquesito7 approved these changes

2022-02-04 00:09 UTC, merged