fix: add Ludovico Sforza
EddieHubCommunity/awesome-github-profiles pull request #1011
Opened 2022-02-09 08:58 UTC by LudovicoSforza

resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-02-09 08:58 UTC, LudovicoSforza commented
resolve #1010

2022-02-09 15:27 UTC, Panquesito7 requested changes

2022-02-09 15:27 UTC, Panquesito7 commented on profiles/LudovicoSforza.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-02-10 14:38 UTC, Panquesito7 approved these changes

2022-02-10 14:50 UTC, merged