fix: add dunggramer
EddieHubCommunity/awesome-github-profiles pull request #1046
Opened 2022-02-21 20:10 UTC by DungGramer

resolves #1045

## Checklist for profile addition

- [x] Name the PR `fix: add <dunggramer>`.
- [x] You've added file named `dunggramer.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-02-22 04:38 UTC, Panquesito7 requested changes

2022-02-22 04:38 UTC, Panquesito7 commented on profiles/dunggramer.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-02-24 13:34 UTC, vikasganiga05 approved these changes
LGTM :+1: Your GitHub profile looks cool :ok_hand:

2022-02-24 14:23 UTC, Panquesito7 approved these changes

2022-02-24 14:23 UTC, schmelto approved these changes

2022-02-24 14:23 UTC, merged