fix: add Preethi-Dev
EddieHubCommunity/awesome-github-profiles pull request #1067
Opened 2022-03-09 09:33 UTC by Preethi-Dev

resolves #1066 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

```diff
+ {
+ "image": "https://user-images.githubusercontent.com/69065327/157410259-299c51b3-582f-42e8-801c-8fefa711fee5.png",
+ "issueId":  1066,
+ "name": "Preethi",
+ "username": "Preethi-Dev"
+ }
```

2022-03-09 12:46 UTC, schmelto commented on profiles/Preethi-Dev.json
> +  "issueId":  1066,
```suggestion
  "issueId": 1066,
```

2022-03-09 14:07 UTC, schmelto approved these changes
lgtm

2022-03-09 14:24 UTC, Panquesito7 requested changes

2022-03-11 15:41 UTC, Panquesito7 approved these changes

2022-03-11 15:43 UTC, merged