add souravsk
EddieHubCommunity/awesome-github-profiles pull request #1069
Opened 2022-03-10 08:14 UTC by souravsk

issue Number :- #1068

resolves #issueNumber

## Checklist for a profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-03-10 09:28 UTC, schmelto approved these changes

2022-03-10 14:20 UTC, Panquesito7 requested changes

2022-03-10 19:03 UTC, vikasganiga05 approved these changes
LGTM :+1: Add the endline.

2022-03-11 15:33 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-03-11 15:34 UTC, merged