fix: add zaira
EddieHubCommunity/awesome-github-profiles pull request #1111
Opened 2022-05-06 11:45 UTC by zairahira

resolves [#1110](https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1110)

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-05-06 12:32 UTC, vikasganiga05 requested changes
Hi, the `issueId` is wrong and you forgot to change `name` & `username` with yours.

2022-05-06 12:32 UTC, vikasganiga05 commented on profiles/zaira.json
> +  "username": "eddiejaoude"
```suggestion
  "issueId": 1110,
  "name": "Zaira Hira",
  "username": "zairahira"
```
Forgot to change it to your credentials.

2022-05-06 14:44 UTC, zairahira commented
@vikasganiga05, thank you for suggesting the change, I missed that.

2022-05-06 16:07 UTC, Panquesito7 approved these changes

2022-05-07 00:36 UTC, vikasganiga05 requested changes
The file name should be `your-github-username.json`. Rename `zaira.json` to `zairahira.json`.

2022-05-07 15:02 UTC, vikasganiga05 approved these changes
LGTM :+1: Thanks for contributing.

2022-05-08 05:10 UTC, krshkodes approved these changes
Thanks for the contribution! Looks awesome!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient, Elegant, Maintainable

2022-05-10 10:40 UTC, Pradumnasaraf approved these changes
Look good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-02 05:18 UTC, merged