fix: add takanome-dev
EddieHubCommunity/awesome-github-profiles pull request #1114
Opened 2022-05-07 15:30 UTC by TAKANOME-DEV

resolves #1113 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes
- `takanome-dev.json` file has been added

## Notes

2022-05-08 00:12 UTC, Panquesito7 requested changes

2022-05-08 00:12 UTC, Panquesito7 commented on profiles/takanome-dev.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-08 05:32 UTC, krshkodes requested changes
After Panquesito's suggestion, it should be good!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Readable, Not maintainable

2022-05-08 20:20 UTC, TAKANOME-DEV commented
Glad to hear from you, endline added. Thanks

2022-05-14 13:16 UTC, TAKANOME-DEV commented
@Panquesito7,  all changes have been made ☺️

2022-05-15 04:09 UTC, Panquesito7 approved these changes

2022-06-02 05:19 UTC, merged