fix: add SubhadeepZilong
EddieHubCommunity/awesome-github-profiles pull request #1133
Opened 2022-05-27 16:31 UTC by SubhadeepZilong

resolves #1132

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-05-27 18:07 UTC, Panquesito7 requested changes

2022-05-27 18:07 UTC, Panquesito7 commented on profiles/SubhadeepZilong.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-28 02:39 UTC, Panquesito7 commented on profiles/SubhadeepZilong.json
> +    "username": "SubhadeepZilong"
I think the indentation space should be 2 in here.
```suggestion
  "image": "https://user-images.githubusercontent.com/63146468/170739449-df9a415d-7b8a-41cc-9891-5ac2d26cce86.png",
  "issueId": 1132,
  "name": "Subhadeep Chakraborty",
  "username": "SubhadeepZilong"
```

2022-05-30 08:53 UTC, schmelto approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-30 17:14 UTC, Pradumnasaraf approved these changes
Looks good to me, thank you for your contribution

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

2022-05-30 22:50 UTC, merged