fix: add abhinavkashyap061
EddieHubCommunity/awesome-github-profiles pull request #1143
Opened 2022-05-29 10:10 UTC by abhinavkashyap061

resolves #1142 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-05-30 15:51 UTC, Panquesito7 requested changes

2022-05-30 15:51 UTC, Panquesito7 commented on profiles/abhinavkashyap061.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-31 08:30 UTC, schmelto approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-31 08:42 UTC, abhinavkashyap061 commented
- ok thanks! do I need to do anything else?? i am a newbie open source contributor 😅

2022-05-31 11:36 UTC, schmelto commented
> * ok thanks! do I need to do anything else?? i am a newbie open source contributor 😅

No all good. Just wait for another maintainer to approve the PR and than this will get merged.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-01 02:15 UTC, Pradumnasaraf approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-01 02:34 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-06-01 02:36 UTC, merged