fix: add devpatricia
EddieHubCommunity/awesome-github-profiles pull request #1169
Opened 2022-06-13 08:19 UTC by devPatricia

resolve #issueNumber #1168

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-13 16:17 UTC, Pradumnasaraf requested changes
Hey! Everything looks good, but some minor changes needed :smile: 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-13 16:17 UTC, Pradumnasaraf commented on profiles/patriciadiaz.json
> +
```suggestion
}
```

2022-06-14 15:19 UTC, pranay202 commented
Hey @devPatricia, everything looks good. Just add one extra line at the end of the code.

2022-06-14 17:05 UTC, Pradumnasaraf requested changes
Everything looks good to me, just add one extra line!

2022-06-14 17:05 UTC, Pradumnasaraf commented on profiles/patriciadiaz.json
> +}
```suggestion
}

```

2022-06-15 03:45 UTC, Panquesito7 requested changes

2022-06-15 03:45 UTC, Panquesito7 commented on profiles/patriciadiaz.json
> +    "username": "devpatricia"
The indentation seems to be wrong here.
```suggestion
  "image": "https://user-images.githubusercontent.com/15069545/173307507-7917cca8-4dba-465b-bb3c-321d82cb5997.png",
  "issueId": 1168,
  "name": "Patricia",
  "username": "devpatricia"
```

2022-06-16 16:43 UTC, Panquesito7 approved these changes

2022-06-18 07:59 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-06-18 07:59 UTC, merged