enn-dee
EddieHubCommunity/awesome-github-profiles pull request #1171
Opened 2022-06-13 10:41 UTC by enn-dee

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-13 12:50 UTC, MrKrishnaAgarwal approved these changes
Looks Great👍🏻

2022-06-13 13:19 UTC, Pradumnasaraf requested changes
Hey!

The issue number #1168  you provided is opened but someone else, and I can't find an issue opened by you. Please open an issue and also modify the image link as well. 

If you have any doubt feel free to reach out



__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-13 13:23 UTC, MrKrishnaAgarwal commented
> Hey!
> 
> The issue number #1168 you provided is opened but someone else, and I can't find an issue opened by you. Please open an issue and also modify the image link as well.
> 
> If you have any doubt feel free to reach out
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Oh Yes, I didn't saw that one.

2022-06-13 16:14 UTC, Pradumnasaraf approved these changes
Looks good to merge, thank you for your contribution!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

2022-06-13 16:24 UTC, MrKrishnaAgarwal approved these changes
Your Profile Looks Great 👍
All the best for the future
Keep Contributing
Also thanks for giving me the chance for reviewing

2022-06-13 17:10 UTC, Panquesito7 requested changes

2022-06-13 17:10 UTC, Panquesito7 commented on profiles/enn-dee.json
> +  "image": "https://user-images.githubusercontent.com/89350768/173366815-a919027a-2c53-4b9d-a029-ef0dbb2ede27.png",
It looks like the image link is different from the issue. Do you want to change it?
```suggestion
  "image": "https://user-images.githubusercontent.com/89350768/173365612-f5ddec29-c3f8-4bc4-a616-d9d0fa2ea6fd.png",
```

2022-06-14 17:04 UTC, Pradumnasaraf approved these changes
Looks good to merge!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

2022-06-18 17:47 UTC, kabir0x23 approved these changes
Looks good 👍
Nice profile 🚀

2022-06-18 18:29 UTC, merged