fix: add amity-ak97
EddieHubCommunity/awesome-github-profiles pull request #1178
Opened 2022-06-13 19:20 UTC by amity-ak97

resolves #1177

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-13 19:25 UTC, Panquesito7 commented on profiles/amity-ak97.json
> +    "image": "https://user-images.githubusercontent.com/54621148/173427837-88c62bfa-34c4-4228-9103-5cc201514d21.png",
I recommend more of an image like this. What do you think?

![image](https://user-images.githubusercontent.com/51391473/173429345-e8914595-0281-4f1b-bded-afea0f6db842.png)

```suggestion
    "image": "https://user-images.githubusercontent.com/51391473/173429345-e8914595-0281-4f1b-bded-afea0f6db842.png",
```

2022-08-01 20:42 UTC, Panquesito7 requested changes

2022-08-01 20:42 UTC, Panquesito7 commented on profiles/amity-ak97.json
> +    "username": "amity-ak97"
It looks like there's a 4-space indentation.
```suggestion
  "image": "https://user-images.githubusercontent.com/51391473/173429345-e8914595-0281-4f1b-bded-afea0f6db842.png",
  "issueId": 1177,
  "name": "Amit Kumar Yadav",
  "username": "amity-ak97"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-08 02:04 UTC, Panquesito7 commented on profiles/amity-ak97.json
> +  "image": "https://user-images.githubusercontent.com/51391473/173429345-e8914595-0281-4f1b-bded-afea0f6db842.png",
I recommend more of an image like this. What do you think? 🙂

![image](https://user-images.githubusercontent.com/51391473/183324033-a83244ff-f987-4bf1-a792-9965b6c20a2d.png)

```suggestion
  "image": "https://user-images.githubusercontent.com/51391473/183324033-a83244ff-f987-4bf1-a792-9965b6c20a2d.png",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

2022-08-08 12:00 UTC, AvidCoder101 approved these changes
LGTM

2022-08-08 12:01 UTC, AvidCoder101 commented
Sorry about that, reviewed on the wrong PR.

2022-08-24 18:00 UTC, merged