fix: add ksaurabh4
EddieHubCommunity/awesome-github-profiles pull request #1180
Opened 2022-06-14 15:56 UTC by ksaurabh4

resolves #https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1179

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-14 17:18 UTC, Pradumnasaraf requested changes
I will recommend using this image,as your profile looks much better in this :)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Reusable

2022-06-14 17:18 UTC, Pradumnasaraf commented on profiles/kumar-saurabh.json
> +  "image": "https://user-images.githubusercontent.com/36674657/173618063-c0a0005f-03d5-4ba8-a711-e2807ca9d310.png",
```suggestion
  "image": "https://user-images.githubusercontent.com/51878265/173637457-4de9897f-46bd-479b-b8d5-ff84f6ca13ae.png",
```

2022-06-15 03:46 UTC, Panquesito7 approved these changes
👍 after @Pradumnasaraf's suggestion.

2022-06-16 01:56 UTC, ksaurabh4 commented
> I will recommend using this image,as your profile looks much better in this :)
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Reusable

Thanks for the suggested Image 👍 I have committed the suggested change as well.

2022-06-17 08:52 UTC, Pradumnasaraf approved these changes
Thank you for the suggested changes. Looks good to merge 👍 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-17 08:53 UTC, merged