fix: add KaranChandekar
EddieHubCommunity/awesome-github-profiles pull request #1192
Opened 2022-06-19 15:39 UTC by KaranChandekar

resolves #1191 

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-19 15:46 UTC, KaranChandekar commented
Please review my pull request!

2022-06-19 17:34 UTC, Panquesito7 requested changes

2022-06-19 17:34 UTC, Panquesito7 commented on profiles/KaranChandekar.json
> +
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-06-20 06:02 UTC, Panquesito7 approved these changes
Amazing! Thank you. 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Elegant

2022-06-20 06:03 UTC, merged

2022-06-20 06:11 UTC, KaranChandekar commented
@Panquesito7 It's mine pleasure!