fix: add Adit0507
EddieHubCommunity/awesome-github-profiles pull request #1197
Opened 2022-06-20 18:33 UTC by Adit0507

resolves #1185 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-20 19:37 UTC, Panquesito7 requested changes

2022-06-20 19:37 UTC, Panquesito7 commented on profiles/Adit0507.json
> +
Wrong indentation and missing an endline. This should fix it. 🙂
```suggestion
  "image": "https://user-images.githubusercontent.com/78037846/174435896-610e56c8-ecec-479b-b572-014a7873de6b.PNG",
  "issueId": 1185,
  "name": "Aditya Kumar Singh",
  "username": "Adit0507"
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-20 19:40 UTC, Adit0507 commented
I just did that, is it working fine now ?

2022-06-20 22:21 UTC, schmelto commented on profiles/Adit0507.json
> +"username": "Adit0507"
```suggestion
  "image": "https://user-images.githubusercontent.com/78037846/174435896-610e56c8-ecec-479b-b572-014a7873de6b.PNG",
  "issueId": 1185,
  "name": "Aditya Kumar Singh",
  "username": "Adit0507"
```

2022-06-21 06:00 UTC, Adit0507 commented
I hope the indentation is fine now

2022-06-26 01:15 UTC, merged