fix: add dhrumishah
EddieHubCommunity/awesome-github-profiles pull request #1204
Opened 2022-06-25 11:55 UTC by dhrumishah

resolves #1203

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-06-25 14:47 UTC, Pradumnasaraf requested changes
Hey! please add a line blank line below!!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-26 03:24 UTC, dhrumishah commented
Is it okay now? @Pradumnasaraf

2022-06-26 03:28 UTC, Pradumnasaraf requested changes
Thank you for the previous changes @dhrumishah, there is still a small indentation issue that the linter caught and an extra parenthesis. Please add those changes, or you also simply do `commit suggestions`

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-06-26 03:28 UTC, Pradumnasaraf commented on profiles/dhrumishah.json
> +}
```suggestion
{
  "image": "https://user-images.githubusercontent.com/84569241/175770956-55116be8-46cb-470c-99b2-1b597158e1c6.png)",
  "issueId": 1203,
  "name": "Dhrumi Shah",
  "username": "dhrumishah"
}
```

2022-06-26 06:01 UTC, dhrumishah commented
> Thank you for the previous changes @dhrumishah, there is still a small indentation issue that the linter caught and an extra parenthesis at the end `https:......png)`. Please add those changes, or you also simply do `commit suggestions`
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

I have resolved the above changes. please do let me know if it has any error.

2022-06-26 06:03 UTC, Pradumnasaraf approved these changes
Thank you for the changes. All checks are now passed.
Looks good to merge :+1: 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

2022-06-26 14:01 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

2022-06-26 14:01 UTC, merged