fix: add nair0lf32
EddieHubCommunity/awesome-github-profiles pull request #1208
Opened 2022-06-25 20:29 UTC by nair0lf32

resolve #1207

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

2022-06-25 23:38 UTC, schmelto commented on profiles/nair0lf32.json
> +    "name": "EDEMESSI Florian",
```suggestion
    "name": "Edemessi Florian",
```

2022-06-26 00:18 UTC, Panquesito7 requested changes

2022-06-26 00:18 UTC, Panquesito7 commented on profiles/nair0lf32.json
> +    "username": "nair0lf32"
Looks like the indentation here is wrong.
```suggestion
  "image": "https://user-images.githubusercontent.com/35136136/175789287-a0796936-1bf8-443c-8adc-f56c4ebb95bc.png",
  "issueId": 1207,
  "name": "EDEMESSI Florian",
  "username": "nair0lf32"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-06-26 07:15 UTC, Pradumnasaraf approved these changes
Looks good to merge :tada: 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-26 14:11 UTC, Panquesito7 approved these changes
Awesome, thanks! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient, Elegant

2022-06-26 14:16 UTC, merged