fix :add Amandeep404
EddieHubCommunity/awesome-github-profiles pull request #1228
Opened 2022-07-13 12:30 UTC by Amandeep404

resolves #1227

## Checklist for profile addition

- [x ] Name the PR `fix: add <your-username>`.
- [x ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ x] Changes made in this PR are mentioned below
- [x ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ x] I acknowledge that all my contributions will be made under the project's license.
- [ x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-07-13 12:39 UTC, Amandeep404 commented
whats the problem in this?

2022-07-14 04:53 UTC, Panquesito7 requested changes

2022-07-14 04:53 UTC, Panquesito7 commented on profiles/Amandeep.json
> +    "username": "Amandeep404"
The indentation seems to be wrong here.
```suggestion
  "image": "https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1227#issue-1303348005",
  "issueId": 1227,
  "name": "Amandeep Singh",
  "username": "Amandeep404"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-07-18 09:40 UTC, Amandeep404 commented
I committed your changes but still the same error...y🥲

2022-07-21 19:52 UTC, SohamRatnaparkhi requested changes
Follow a `2 space` indentation for lines `2 to 5` over the 4 space indentation that you have made!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-07-23 06:03 UTC, Amandeep404 commented
> Follow a `2 space` indentation for lines `2 to 5` over the 4 space indentation that you have made!
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Inefficient

I guess I have given only two space indentation and not 4

2022-07-24 04:30 UTC, Panquesito7 approved these changes
Thank you for your valuable contribution! 🎉
Code looks good. Not sure why the prettier is failing, though. 🤔


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-03 17:35 UTC, Pradumnasaraf approved these changes

2022-08-03 17:39 UTC, Pradumnasaraf requested changes
Hey, 
Sorry for approving it at first (The wrong button clicked). Your current screenshot doesn't contain a profile picture also you have to a screenshot of your profile page instead of issue one. So you can update the new one. If you have any issues, let's know

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-03 18:11 UTC, closed without merging