fix: add ayushlohmod
EddieHubCommunity/awesome-github-profiles pull request #1230
Opened 2022-07-13 15:18 UTC by ayushlohmod

resolves #1229

2022-07-13 18:33 UTC, Panquesito7 requested changes

2022-07-13 18:33 UTC, Panquesito7 commented on profiles/ayushlohmod.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-07-15 17:09 UTC, Panquesito7 requested changes

2022-07-15 17:09 UTC, Panquesito7 commented on profiles/ayushlohmod.json
> +"username": "ayushlohmod"
It's missing a **two-space** indentation.
```suggestion
  "image": "https://user-images.githubusercontent.com/37297939/178766012-d773a89b-8627-4ca7-bdad-5def06995121.png",
  "issueId": 1229,
  "name": "Ayush Lohmod",
  "username": "ayushlohmod"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-07-16 16:53 UTC, ayushlohmod reviewed
please have a look on this

2022-07-17 15:42 UTC, Panquesito7 approved these changes
Thanks for contributing! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient, Elegant

2022-07-18 13:19 UTC, merged