fix: add Exoutia
EddieHubCommunity/awesome-github-profiles pull request #1248
Opened 2022-07-21 08:02 UTC by Exoutia

resolves #1247 

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-07-21 13:04 UTC, kaiwalyakoparkar requested changes
It seems like there is a prettier error. Please follow 2 space indentation rather than 4

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-21 14:39 UTC, Exoutia commented
Ok

2022-07-22 07:24 UTC, schmelto approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-23 12:42 UTC, kaiwalyakoparkar approved these changes
lgtm 🚀 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-23 13:05 UTC, Exoutia commented
@kaiwalyakoparkar but it's still failing prettier test 🥲🥲

2022-07-23 13:51 UTC, kaiwalyakoparkar commented
> @kaiwalyakoparkar but it's still failing prettier test 🥲🥲

I re-run the action but it still says failed. This might be an action issue. Don't worry once confirmed your pr will be merged :)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-25 12:18 UTC, schmelto commented on profiles/Exoutia.json
> +  "image": "https://user-images.githubusercontent.com/94464106/180158833-d731794f-9099-4be7-a118-044c90bb1317.png",
```suggestion
  "image": "https://user-images.githubusercontent.com/94464106/180158833-d731794f-9099-4be7-a118-044c90bb1317.png",
```

2022-07-25 12:18 UTC, schmelto commented on profiles/Exoutia.json
> +  "username": "Exoutia"
```suggestion
  "issueId": 1247,
  "name": "Bibek Jha",
  "username": "Exoutia"
```

2022-07-25 12:21 UTC, schmelto commented on profiles/Exoutia.json
> +}
```suggestion
{
  "image": "https://user-images.githubusercontent.com/94464106/180158833-d731794f-9099-4be7-a118-044c90bb1317.png",
  "issueId": 1247,
  "name": "Bibek Jha",
  "username": "Exoutia"
}

```

2022-07-25 12:22 UTC, merged