fix: add marcokumu
EddieHubCommunity/awesome-github-profiles pull request #1269
Opened 2022-07-30 09:41 UTC by marcokumu

resolves #1268 

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-07-30 09:46 UTC, marcokumu commented
Thanks.

2022-08-01 04:22 UTC, Panquesito7 requested changes

2022-08-01 04:22 UTC, Panquesito7 commented on profiles/marcokumu.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-01 04:22 UTC, Panquesito7 commented on profiles/marcokumu.json
> +    "username": "marcokumu"
There seems to be a 4-space indentation. We use a 2-space indentation.
```suggestion
  "image": "https://user-images.githubusercontent.com/90620737/181904436-f701dab8-5940-4572-951d-4c714cbca8ee.png",
  "issueId": 1268,
  "name": "Okumu Mark",
  "username": "marcokumu"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-01 07:35 UTC, marcokumu commented
The requested changes have been made.

2022-08-01 20:34 UTC, Panquesito7 approved these changes
Thanks for contributing! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-01 20:37 UTC, merged