fix: add Amandeep404
EddieHubCommunity/awesome-github-profiles pull request #1279
Opened 2022-08-03 18:45 UTC by Amandeep404

resolves #1278

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-08-03 18:48 UTC, Amandeep404 commented
why my code is failing during the prettier check? how can I solve this issue? any guidance?

2022-08-03 19:34 UTC, RayanAbid commented
I think you have to remove the ``Other additions/changes `` Section

2022-08-03 20:35 UTC, Panquesito7 requested changes

2022-08-03 20:35 UTC, Panquesito7 commented on profiles/Amandeep.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
This should also fix the Prettier (or Continuous Integration) issues.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-04 16:23 UTC, Amandeep404 commented
thanks :)

2022-08-04 16:25 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-04 16:26 UTC, merged