fix: add razaahmad333
EddieHubCommunity/awesome-github-profiles pull request #1286
Opened 2022-08-05 06:11 UTC by razaahmad333

resolves #1285 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-08-05 18:57 UTC, Panquesito7 requested changes

2022-08-05 18:57 UTC, Panquesito7 commented on profiles/razaahmad333.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-05 18:57 UTC, Panquesito7 commented on profiles/razaahmad333.json
> +    "username":"razaahmad333"
Looks like there's a 4-space indentation here. We use a 2-space indentation.
```suggestion
  "image":"https://user-images.githubusercontent.com/50910798/183011422-78c51113-785f-4a46-91ca-573693de64bf.png",
  "issueId":1285,
  "name":"Ahmad Raza",
  "username":"razaahmad333"   
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-07 00:09 UTC, Panquesito7 requested changes

2022-08-07 00:09 UTC, Panquesito7 commented on profiles/razaahmad333.json
> +
There's an extra line here. GitHub doesn't display the endline.
```suggestion
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-07 18:29 UTC, Pradumnasaraf approved these changes
Looks good to merge!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-08 02:08 UTC, Panquesito7 requested changes

2022-08-08 02:08 UTC, Panquesito7 commented on profiles/razaahmad333.json
> +  "username":"razaahmad333"
I think we need to add these extra spaces here.
```suggestion
  "image": "https://user-images.githubusercontent.com/50910798/183011422-78c51113-785f-4a46-91ca-573693de64bf.png",
  "issueId" :1285,
  "name": "Ahmad Raza",
  "username": "razaahmad333"   
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-08 15:21 UTC, Panquesito7 requested changes

2022-08-08 15:21 UTC, Panquesito7 commented on profiles/razaahmad333.json
> +  "username": "razaahmad333"
Trailing whitespace.
```suggestion
  "username": "razaahmad333"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-08 15:28 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-08-08 15:29 UTC, merged

2022-08-08 15:59 UTC, razaahmad333 commented
> Thanks for contributing! 🎉
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good  |  **Tags:** Elegant

its my pleasure