fix: add anekemichael
EddieHubCommunity/awesome-github-profiles pull request #1291
Opened 2022-08-09 15:08 UTC by anekemichael

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-08-09 15:14 UTC, anekemichael reviewed
resolve #1309

2022-08-09 16:49 UTC, Pradumnasaraf requested changes
Hey, 
Open your issue and use that issue no, instead of someone other.

If you need any help feel free to reach out.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-10 16:03 UTC, anekemichael commented
Hey, Please how can i do that..?? I'm new here please

2022-08-11 17:43 UTC, Pradumnasaraf reviewed
Hey, you go on the issue section of this repo (https://github.com/EddieHubCommunity/awesome-github-profiles/issues) and create an issue, then add that to PR. 

Also, there is a full guide in the readme. 
![Screenshot from 2022-08-11 23-12-06](https://user-images.githubusercontent.com/51878265/184198851-d80cd499-4db9-44c3-96d8-a96151ea3e01.png)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-16 11:09 UTC, MrKrishnaAgarwal requested changes
**Create the issue [here](https://github.com/EddieHubCommunity/awesome-github-profiles/issues/new?assignees=&labels=&template=add-an-awesome-github-profile.md&title=Aneke-Michael)** and submit the correct `issue Id`

2022-08-17 01:47 UTC, Panquesito7 requested changes

2022-08-17 01:47 UTC, Panquesito7 commented on profiles/anekemichael.json
> +  "issueId": 66,
This should be the correct issue ID: #1309.
```suggestion
  "issueId": 1309,
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-17 06:13 UTC, anekemichael commented
Thanks so much

On Wed, Aug 17, 2022 at 2:47 AM David Leal ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In profiles/anekemichael.json
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1291#discussion_r947379031>
> :
>
> > @@ -0,0 +1,6 @@
>
> +{
>
> +  "image": "https://user-images.githubusercontent.com/62024664/183684520-33c4059b-d4cc-4404-bfc9-9407370944e3.png",
>
> +  "issueId": 66,
>
>
> This should be the correct issue ID: #1309
> <https://github.com/EddieHubCommunity/awesome-github-profiles/issues/1309>
> .
> ⬇️ Suggested change
>
> -  "issueId": 66,
>
> +  "issueId": 1309,
>
>
> __
> [image: sema-logo] <https://semasoftware.com/gh>  *Summary:* 🛠️ This
> code needs a fix  |  *Tags:* Not maintainable
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1291#pullrequestreview-1074946168>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOZGXWGYLNGV2RNQ7KV7O5DVZRADXANCNFSM56BE4LRQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: <EddieHubCommunity/awesome-github-profiles/pull/1291/review/1074946168
> @github.com>
>

2022-08-17 06:54 UTC, schmelto approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-17 06:59 UTC, anekemichael commented
Thanks so much guys.. y'all are the best

On Wed, Aug 17, 2022 at 7:55 AM Tom Schmelzer ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> __
> [image: sema-logo] <https://semasoftware.com/gh>  *Summary:* 👌 This code
> looks good
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1291#pullrequestreview-1075129529>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOZGXWHBTOENSVAGMKDYZMTVZSEEJANCNFSM56BE4LRQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: <EddieHubCommunity/awesome-github-profiles/pull/1291/review/1075129529
> @github.com>
>

2022-08-17 12:59 UTC, MrKrishnaAgarwal approved these changes
don't close it again and again
they'll merge the pr soon.

2022-08-17 13:03 UTC, anekemichael commented
Ok.. Thanks

On Wed, Aug 17, 2022 at 1:59 PM Krishna Agarwal ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> don't close it again and again
> they'll merge the pr soon.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1291#pullrequestreview-1074566355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOZGXWAPHSVC2DY3I3OCY2TVZTO2FANCNFSM56BE4LRQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: <EddieHubCommunity/awesome-github-profiles/pull/1291/review/1074566355
> @github.com>
>

2022-08-17 20:41 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-17 20:43 UTC, merged

2022-08-18 06:09 UTC, anekemichael commented
Awesome, thanks!

On Wed, Aug 17, 2022 at 9:43 PM David Leal ***@***.***> wrote:

> Merged #1291
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1291>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1291#event-7209124620>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOZGXWC33SDI7SVNPWU4HI3VZVFHRANCNFSM56BE4LRQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID:
> <EddieHubCommunity/awesome-github-profiles/pull/1291/issue_event/7209124620
> @github.com>
>

2022-08-18 06:15 UTC, anekemichael commented
Please, how can i add my profile to the profile.md page.?