fix: Add sachinparihar
EddieHubCommunity/awesome-github-profiles pull request #1293
Opened 2022-08-10 08:28 UTC by sachinparihar

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-08-11 17:40 UTC, Pradumnasaraf requested changes
Hey, 
Everything looks good, just minor indentation issues.

2022-08-11 17:40 UTC, Pradumnasaraf commented on profiles/sachinparihar.json
> +  }
```suggestion
{
  "image": "https://user-images.githubusercontent.com/94243074/183848297-0cd1bd02-e62d-4ce0-90ec-3d557a394111.png",
  "issueId": 1292,
  "name": "Sachin Parihar",
  "username": "sachinparihar"
  }
```

2022-08-12 18:49 UTC, Panquesito7 requested changes

2022-08-12 18:49 UTC, Panquesito7 commented on profiles/sachinparihar.json
> +
There's an extra space here. GitHub doesn't display the endline.
```suggestion
}
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-14 08:01 UTC, Pradumnasaraf approved these changes
Looks good to merge!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

2022-08-15 20:16 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-15 20:17 UTC, merged