Create poonam-adlakha.json
EddieHubCommunity/awesome-github-profiles pull request #1297
Opened 2022-08-12 12:54 UTC by poonam-adlakha

Adding my profile to list of Awesome-GitHub-profiles

resolves #1

## Checklist for profile addition

- [ ] Name the PR `fix: poonam-adlakha`.
- [ ] You've added file named `poonam-adlakha.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-08-14 08:00 UTC, Pradumnasaraf requested changes
Hey,

The issue number you mentioned is not associated with you. Open an issue with the steps given in the [README](https://github.com/EddieHubCommunity/awesome-github-profiles/) and then add it here.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-08-15 09:29 UTC, Pradumnasaraf approved these changes
Thank you for the changes, Poonam. Looks good to merge!

2022-08-15 09:31 UTC, AvidCoder101 approved these changes

2022-08-15 20:06 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-15 20:12 UTC, merged