fix: add gambhirsharma
EddieHubCommunity/awesome-github-profiles pull request #1299
Opened 2022-08-12 14:54 UTC by gambhirsharma

resolves #1298 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

2022-08-12 18:36 UTC, Panquesito7 requested changes

2022-08-12 18:36 UTC, Panquesito7 commented on profiles/gambhirsharma.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-12 20:25 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-13 08:33 UTC, gambhirsharma commented
Can I close this issue?

2022-08-13 09:21 UTC, AvidCoder101 commented
@gambhirsharma no, don't close the issue as the PR needs to be merged first. After the PR has been merged, then a maintainer will close the issue. Hope that helps.

2022-08-13 09:21 UTC, AvidCoder101 approved these changes

2022-08-13 09:24 UTC, schmelto approved these changes

2022-08-13 09:24 UTC, merged