fix: add makendrang
EddieHubCommunity/awesome-github-profiles pull request #1317
Opened 2022-08-20 12:27 UTC by MakendranG

resolve #1316

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-08-21 17:48 UTC, Panquesito7 requested changes

2022-08-21 17:48 UTC, Panquesito7 commented on profiles/makendrang.json
> +![image](https://user-images.githubusercontent.com/74320000/185746011-a5c06825-183d-4dc3-abd5-bd057098381e.png)
Please remove this line.
```suggestion
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-22 06:58 UTC, MakendranG commented
Suggested changes have been done.

2022-08-22 07:26 UTC, schmelto requested changes

2022-08-22 07:26 UTC, schmelto commented on profiles/makendrang.json
> +
```suggestion
```

2022-08-22 07:26 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-08-23 16:41 UTC, Panquesito7 approved these changes
Thanks for contributing! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-23 16:43 UTC, merged