my profile
EddieHubCommunity/awesome-github-profiles pull request #1363
Opened 2022-09-05 09:25 UTC by yigagilbert

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-09-05 09:29 UTC, yigagilbert commented
fix: add yiga gilbert

2022-09-05 18:14 UTC, Pradumnasaraf requested changes

2022-09-06 14:51 UTC, yigagilbert commented on profiles/yigagilbert.json
> +  "issueId": 66,
i tried it out but I dont what failed it

2022-09-07 14:10 UTC, Panquesito7 requested changes

2022-09-07 14:10 UTC, Panquesito7 commented on profiles/yigagilbert.json
> +  "issueId": 66,
It seems the issue is #1362.
```suggestion
  "issueId": 1362,
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-11-07 18:28 UTC, merged