fix: add milkshakegum
EddieHubCommunity/awesome-github-profiles pull request #1382
Opened 2022-09-16 08:31 UTC by milkshakegum

resolves #1381

## Checklist for profile addition

- [X] Name the PR `fix: add milkshakegum`.
- [X] Added file named `milkshakegum.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [X] You've linked the PR to the correct issue.

2022-09-16 16:26 UTC, Panquesito7 requested changes

2022-09-16 16:26 UTC, Panquesito7 commented on profiles/milkshakegum.json
> +    "issueId": 66,
```suggestion
    "issueId": 1381,
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-09-16 16:26 UTC, Panquesito7 commented on profiles/milkshakegum.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-10-11 17:54 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-10-11 17:55 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-11 17:55 UTC, merged