Create Tooxic.json
EddieHubCommunity/awesome-github-profiles pull request #1433
Opened 2022-10-01 20:17 UTC by Tooxic

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-10-01 20:19 UTC, E-fais approved these changes

2022-10-01 20:19 UTC, E-fais commented on profiles/Tooxic.json
> +{
LGTM

2022-10-01 20:28 UTC, E-fais requested changes
change title of the pull request to;
fix: add Albin Håkanson .
Add a discription as follows:
resolves #1431

2022-10-02 00:12 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉

2022-10-03 18:56 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-03 18:56 UTC, merged