fix: blackkspydo
EddieHubCommunity/awesome-github-profiles pull request #1438
Opened 2022-10-02 02:21 UTC by blackkspydo

resolves #1437

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

2022-10-02 02:35 UTC, Panquesito7 requested changes

2022-10-02 02:35 UTC, Panquesito7 commented on profiles/blackkspydo.json
> +
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-10-03 04:16 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2022-10-03 19:00 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-03 19:00 UTC, merged