fix: add rohit8020
EddieHubCommunity/awesome-github-profiles pull request #1447
Opened 2022-10-02 14:15 UTC by rohit8020

resolves #1446

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-10-02 14:57 UTC, Panquesito7 requested changes

2022-10-02 14:57 UTC, Panquesito7 commented on profiles/rohit8020.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-10-02 16:26 UTC, rohit8020 commented
Added an endline in rohit8020.json

2022-10-02 16:27 UTC, rohit8020 commented
Added an endline in rohit8020.json

2022-10-02 16:42 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2022-10-03 18:46 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-03 18:47 UTC, merged