fix: add pythonhubdev
EddieHubCommunity/awesome-github-profiles pull request #1468
Opened 2022-10-05 14:40 UTC by pythonhubdev

resolves #1467 

## Checklist for a profile addition

- [x] Name the PR `fix: add pythonhubdev`.
- [x] You've added file named `pythonhubdev.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

2022-10-05 14:48 UTC, Panquesito7 requested changes

2022-10-05 14:48 UTC, Panquesito7 commented on profiles/pythonhubdev.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-10-05 16:52 UTC, pythonhubdev commented
@Panquesito7 I have committed the changes

2022-10-05 17:14 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-10-05 17:44 UTC, pythonhubdev commented
@Panquesito7 will this PR be merged?

2022-10-07 16:48 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-07 16:48 UTC, merged