fix:Add Anjuli08
EddieHubCommunity/awesome-github-profiles pull request #1479
Opened 2022-10-08 05:32 UTC by Anjuli08

resolves #1478 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

2022-10-09 15:23 UTC, Panquesito7 requested changes

2022-10-09 15:23 UTC, Panquesito7 commented on profiles/Anjuli08.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-10-10 11:47 UTC, Anjuli08 commented
done! pls review

2022-10-10 14:30 UTC, Panquesito7 commented on profiles/Anjuli08.json
> +
```suggestion
```

2022-10-10 14:34 UTC, Panquesito7 commented on profiles/Anjuli08.json
> +    "username": "Anjuli08"
Should be a two-space indentation.
```suggestion
  "image": "https://user-images.githubusercontent.com/90701800/194690166-9327c711-0e96-4420-a1db-efbbe7807147.png",
  "issueId": 1478,
  "name": "Anjuli Aggarwal",
  "username": "Anjuli08"
```

2022-10-10 17:40 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2022-10-10 17:55 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-10 17:55 UTC, merged

2022-10-22 09:37 UTC, Anjuli08 commented
Thank you!