Create ayushigeorge.json
EddieHubCommunity/awesome-github-profiles pull request #1505
Opened 2022-10-24 09:54 UTC by ayushigeorge

resolves #i1504

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [* ] Changes made in this PR are mentioned below
- [* ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ *] I acknowledge that all my contributions will be made under the project's license.
- [ *] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-10-24 18:30 UTC, Panquesito7 requested changes

2022-10-24 18:30 UTC, Panquesito7 commented on profiles/ayushigeorge.json
> +  "issueId": 66,
```suggestion
  "image": "https://user-images.githubusercontent.com/76419649/197496166-56b35008-600f-4638-8d15-44c788b687b0.jpg",
  "issueId": 1504,
```

2022-12-20 17:05 UTC, ayushigeorge commented
Done the required changes.

2022-12-21 02:35 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-21 19:47 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-21 19:47 UTC, merged