add: syofyanzuhad-profile
EddieHubCommunity/awesome-github-profiles pull request #1515
Opened 2022-10-26 15:54 UTC by syofyanzuhad

2022-10-26 17:10 UTC, Panquesito7 requested changes

2023-01-18 15:01 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-31 09:20 UTC, himanshu1221 approved these changes
Looks Nice to me

2023-01-31 09:23 UTC, schmelto approved these changes

2023-01-31 09:23 UTC, merged