fix: add deveshp007
EddieHubCommunity/awesome-github-profiles pull request #1582
Opened 2022-12-21 05:27 UTC by deveshp007

resolves #issueNumber

## Checklist for profile addition

- [/] Name the PR `fix: add <your-username>`.
- [/] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [/] You've linked the PR to the correct issue.

---

## Other additions/changes

- [/] Changes made in this PR are mentioned below
- [/] Search previous suggestions before making a new one, as yours may be a duplicate.
- [/] I acknowledge that all my contributions will be made under the project's license.
- [/] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-12-21 14:24 UTC, Panquesito7 requested changes

2022-12-21 14:24 UTC, Panquesito7 commented on profiles/deveshp007.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-12-21 21:03 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-23 06:43 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-23 06:43 UTC, merged