Create Bylickilabs.json
EddieHubCommunity/awesome-github-profiles pull request #1589
Opened 2022-12-24 21:34 UTC by bylickilabs

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-12-24 21:39 UTC, krshkun approved these changes
Looks good! Thank you

2022-12-25 06:49 UTC, Panquesito7 requested changes

2022-12-25 06:49 UTC, Panquesito7 commented on profiles/Bylickilabs.json
> +  "issueId": 1589,
I believe the issue ID here must be #1588.
```suggestion
  "issueId": 1588,
```

2022-12-25 20:21 UTC, bylickilabs reviewed
Is it correct now? Please check again

2022-12-25 21:04 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-29 12:14 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-29 12:15 UTC, merged

2023-05-28 11:22 UTC, bylickilabs reviewed
Create on https://github.com/EddieHubCommunity/awesome-github-profiles
bylickilabs.json