fix: add shamilkotta
EddieHubCommunity/awesome-github-profiles pull request #1598
Opened 2022-12-25 16:56 UTC by shamilkotta

resolves #1597

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

2022-12-25 20:54 UTC, Panquesito7 requested changes

2022-12-25 20:54 UTC, Panquesito7 commented on profiles/shamilkotta.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-12-26 03:57 UTC, shamilkotta commented
changes updated please have a look 
Thank you

2022-12-26 22:01 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-29 12:14 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-29 12:14 UTC, merged