Fix:  <AyushJain001>
EddieHubCommunity/awesome-github-profiles pull request #1607
Opened 2023-01-01 18:48 UTC by AyushJain001

resolve #1606

2023-01-01 23:17 UTC, Panquesito7 requested changes

2023-01-01 23:17 UTC, Panquesito7 commented on profiles/AyushJain001.json
> +  "image": "https://user-images.githubusercontent.com/90152799/210181328-0922e8d4-bea4-4643-b1d3-186250b87d94.png",
I recommend more of an image like this. What do you think? 🙂

![image](https://user-images.githubusercontent.com/51391473/210187235-4d9af402-a934-4622-8e68-44a56d4a47c8.png)

```suggestion
  "image": "https://user-images.githubusercontent.com/51391473/210187235-4d9af402-a934-4622-8e68-44a56d4a47c8.png",
```

2023-01-03 09:47 UTC, AyushJain001 commented
Okay I am changing the image

2023-01-03 09:56 UTC, AyushJain001 commented
Updated the requested changes. Kindly check.

2023-01-05 20:03 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-06 07:01 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-01-06 07:01 UTC, merged