Create Priyanshi-Rai.json
EddieHubCommunity/awesome-github-profiles pull request #1633
Opened 2023-01-08 14:54 UTC by Priyanshi-Rai

resolves #1630

## Checklist for profile addition

- [x] Name the PR `fix: add <Priyanshi-Rai>`.
- [x] You've added file named `Priyanshi-Rai.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-01-09 18:59 UTC, Panquesito7 requested changes

2023-01-09 18:59 UTC, Panquesito7 commented on profiles/Priyanshi-Rai.json
> +
There's an extra line here that should be removed.
```suggestion
```

2023-01-10 18:11 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-12 08:07 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-01-12 08:07 UTC, merged