add thelabuzov
EddieHubCommunity/awesome-github-profiles pull request #1640
Opened 2023-01-10 15:59 UTC by thelabuzov

resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## This PR adds/fixes

## Notes

2023-01-10 16:22 UTC, Panquesito7 requested changes

2023-01-10 16:22 UTC, Panquesito7 commented on profiles/thelabuzov.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-01-11 01:56 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1640/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](http://discord.eddiehub.org). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

2023-01-13 16:38 UTC, Panquesito7 reviewed
Hmm. What's the difference between the old and the changed code? I don't see any difference. 🤔

2023-02-06 14:53 UTC, Pradumnasaraf reviewed
There is no difference in the changes and the PR is open for a while, so closing it. Feel free to raise a new one.

2023-02-06 14:53 UTC, closed without merging