fix: add Im-vishalanand
EddieHubCommunity/awesome-github-profiles pull request #1641
Opened 2023-01-10 23:12 UTC by Im-vishalanand

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-01-11 04:33 UTC, Panquesito7 requested changes

2023-01-11 04:33 UTC, Panquesito7 commented on profiles/Im-vishalanand.json
> +    "issueId": 2701,
You must create a [valid issue](https://github.com/EddieHubCommunity/awesome-github-profiles/issues/new?assignees=&labels=profile+addition&template=add-an-awesome-github-profile.yml&title=%5BPROFILE+ADDITION%5D+%3Cname+here%3E) for your profile addition.

2023-01-11 04:33 UTC, Panquesito7 commented on profiles/Im-vishalanand.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-01-11 05:43 UTC, Im-vishalanand commented
changes has been done. Let me know if it looks good now.

2023-01-11 14:47 UTC, Panquesito7 requested changes

2023-01-11 14:47 UTC, Panquesito7 commented on profiles/Im-vishalanand.json
> +    "issueId": 1641,
This is the current PR number, which won't work. An [issue](https://github.com/EddieHubCommunity/awesome-github-profiles/issues/new?assignees=&labels=profile+addition&template=add-an-awesome-github-profile.yml&title=%5BPROFILE+ADDITION%5D+%3Cname+here%3E) must be created for that.

2023-01-11 15:01 UTC, Im-vishalanand commented
I got it. Done the changes. Hope it is good now.
Thank you so much for the guidance.

2023-01-11 15:42 UTC, Panquesito7 commented on profiles/Im-vishalanand.json
> +}
Missing an endline here.
```suggestion
}

```

2023-01-12 16:44 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-16 19:06 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-01-16 19:17 UTC, merged