fix: add Rishav1707
EddieHubCommunity/awesome-github-profiles pull request #1650
Opened 2023-01-11 10:40 UTC by Rishav1707

resolves #1649 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

2023-01-11 14:52 UTC, Panquesito7 requested changes

2023-01-11 14:52 UTC, Panquesito7 commented on profiles/Rishav1707.json
> +  "image": "https://avatars.githubusercontent.com/u/97666287?v=4",
Should be the provided image in the issue you created.

```suggestion
  "image": "https://user-images.githubusercontent.com/97666287/211783632-12ef84c0-3f6d-4bf8-850c-234981a2e458.png",
```

2023-01-12 16:45 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-16 04:21 UTC, Rishav1707 commented
> Thanks! 🎉

When did this PR get merged?

2023-01-16 16:49 UTC, Panquesito7 commented
> > Thanks! 🎉
> 
> When did this PR get merged? @Panquesito7

Once another maintainer approves the PR, it will get merged. 🙂

2023-01-16 19:05 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-01-16 19:06 UTC, merged