fix: add Devanshukoli
EddieHubCommunity/awesome-github-profiles pull request #1668
Opened 2023-01-20 07:11 UTC by Devanshukoli

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-01-20 20:04 UTC, Panquesito7 requested changes
Please revert the changes in the other files and keep your profile changes only.
If you need any help doing that, let us know and we'll gladly help. 🙂

2023-01-22 06:10 UTC, Devanshukoli commented
Hey, @Panquesito7 I tried reverting the changes but I used 'git revert HEAD' this is what I used in the terminal and I don't know now what to do? Could you please guide me through it?

2023-01-22 19:01 UTC, Panquesito7 commented
> I don't know now what to do? Could you please guide me through it?

You can copy all the changes from the [original files](https://github.com/EddieHubCommunity/awesome-github-profiles/) and put them in your fork, then only add your profile. 🙂

2023-01-23 16:51 UTC, Devanshukoli commented
@Panquesito7 I have done the changes as you told. So would you kind take a look as well?

2023-01-23 17:32 UTC, Panquesito7 requested changes
Looks like the endlines were modified. Feel free to accept the suggestions by clicking on `Commit suggestion`.

2023-01-23 17:32 UTC, Panquesito7 commented on _layouts/default.html
> +</body>
```suggestion
</body>

```

2023-01-23 17:32 UTC, Panquesito7 commented on generate.js
> +);
```suggestion
);

```

2023-01-23 17:32 UTC, Panquesito7 commented on package-lock.json
> +}
```suggestion
}

```

2023-01-23 17:32 UTC, Panquesito7 commented on package.json
> +}
```suggestion
}

```

2023-01-23 17:32 UTC, Panquesito7 commented on profiles/Devanshukoli.json
> +  }
```suggestion
}

```

2023-01-24 19:34 UTC, Panquesito7 commented on profiles/Devanshukoli.json
> +    "username": "Devanshukoli"
Wrong indentation.
```suggestion
  "image": "https://user-images.githubusercontent.com/99028806/213636924-304e3333-6ab8-426f-a416-410604854df9.png",
  "issueId": 1667,
  "name": "Devanshu Koli",
  "username": "Devanshukoli"
```

2023-01-24 19:36 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2023-01-25 15:42 UTC, Devanshukoli commented
Thanks for the help, It was a really great experience. @Panquesito7

2023-01-26 01:18 UTC, Panquesito7 commented
Not sure you want to close this PR? If you close, you won't be able to get your profile added to the list.

2023-01-26 09:19 UTC, Devanshukoli commented
Ok, got it.

2023-02-03 17:56 UTC, priyankarpal approved these changes
LGTM 👍🏻 ⚡

2023-02-03 17:57 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-03 17:57 UTC, merged

2023-02-03 23:02 UTC, Devanshukoli commented
Yeyy! Thanks for guiding me this through @Panquesito7 and for merging @Pradumnasaraf