fix: add Abhishek-00
EddieHubCommunity/awesome-github-profiles pull request #1671
Opened 2023-01-21 17:31 UTC by Abhishek-00

resolves #1670 
## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-01-22 01:13 UTC, Panquesito7 requested changes

2023-01-22 01:13 UTC, Panquesito7 commented on profiles/Abhishek-00.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-01-22 18:52 UTC, Panquesito7 commented on profiles/Abhishek-00.json
> +
```suggestion
```

2023-01-22 18:54 UTC, Panquesito7 commented on profiles/Abhishek-00.json
> +    "username": "Abhishek-00"
```suggestion
  "image": "https://user-images.githubusercontent.com/101923614/213878832-4282e481-ce0c-4a57-a3e6-6f3eeb688901.png",
  "issueId": 1670,
  "name": "Abhishek Kumar",
  "username": "Abhishek-00"
```

2023-01-22 18:57 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-03 17:47 UTC, priyankarpal approved these changes
LGTM 👍🏻 ⚡

2023-02-06 14:48 UTC, Pradumnasaraf reviewed
Looks good to merge. Thank you for your contribution! :tada:

2023-02-06 14:48 UTC, merged