add: profile - JoseVale99
EddieHubCommunity/awesome-github-profiles pull request #1673
Opened 2023-01-22 06:44 UTC by JoseVale99

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-01-22 19:19 UTC, Panquesito7 requested changes

2023-01-22 19:19 UTC, Panquesito7 commented on profiles/josevale99.json
> +    "image": "https://user-images.githubusercontent.com/39961893/213903888-4347babe-71b8-41b3-b69e-836c1fe87503.png",
I recommend more of an image like this. What do you think? 🙂

![image](https://user-images.githubusercontent.com/51391473/213935618-d8bbd295-4fee-45cb-94d1-5278624b9042.png)

```suggestion
    "image": "https://user-images.githubusercontent.com/51391473/213935618-d8bbd295-4fee-45cb-94d1-5278624b9042.png",
```

2023-01-22 19:19 UTC, Panquesito7 commented on profiles/josevale99.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-01-24 06:20 UTC, JoseVale99 reviewed
fix json

2023-01-24 19:28 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-03 17:42 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-03 17:42 UTC, merged