fix: add Tejender1521
EddieHubCommunity/awesome-github-profiles pull request #1684
Opened 2023-01-24 16:45 UTC by Tejender1521

resolves #67

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-01-24 19:41 UTC, Panquesito7 requested changes

2023-01-24 19:41 UTC, Panquesito7 commented on profiles/Tejender1521.json
> +  "issueId": 67,
Wrong issue ID.
```suggestion
  "issueId": 1683,
```

2023-01-26 01:19 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-31 09:36 UTC, himanshu1221 approved these changes
Looks Nice to me !

2023-02-03 17:40 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-03 17:40 UTC, merged