fix: add <Ajay84sia>
EddieHubCommunity/awesome-github-profiles pull request #1692
Opened 2023-01-31 17:23 UTC by Ajay84sia

resolve #1691

2023-01-31 17:51 UTC, Panquesito7 requested changes

2023-01-31 17:51 UTC, Panquesito7 commented on profiles/Ajay84sia.json
> +  "issueId": 70,
Wrong issue ID.
```suggestion
  "issueId": 1691,
```

2023-02-01 07:54 UTC, Ajay84sia commented
@Panquesito7  my  "issueId": 1691,

2023-02-01 08:59 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-03 17:22 UTC, priyankarpal approved these changes
LGTM 👍🏻 ⚡

2023-02-03 17:28 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-03 17:28 UTC, merged