Create iemsahil
EddieHubCommunity/awesome-github-profiles pull request #1745
Opened 2023-02-23 11:01 UTC by Iemsahil

resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <iemsahil>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-02-23 15:45 UTC, Panquesito7 requested changes
Your newly added file's type should be `.json`.
Please update accordingly. If you need any help, let us know. 🙂

2023-02-23 21:52 UTC, Panquesito7 requested changes

2023-02-23 21:52 UTC, Panquesito7 commented on profiles/iemsahil.json
> +  "image": "https://user-images.githubusercontent.com/88196017/220886003-a73305b9-59c3-4482-bcb7-f709ef90aaed.png",
I recommend more of an image like this. What do you think? 🙂

![image](https://user-images.githubusercontent.com/51391473/221038659-cbb8be57-822d-415a-b084-e0e08ac6f35c.png)

```suggestion
  "image": "https://user-images.githubusercontent.com/51391473/221038659-cbb8be57-822d-415a-b084-e0e08ac6f35c.png",
```

2023-02-23 21:52 UTC, Panquesito7 commented on profiles/iemsahil.json
> +  "issueId": 1745,
Wrong issue ID.
```suggestion
  "issueId": 1743,
```

2023-02-24 06:57 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-04 02:45 UTC, SurajPratap10 approved these changes

2023-03-09 20:46 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-03-09 20:47 UTC, merged