fix: add <AsserELfeki>
EddieHubCommunity/awesome-github-profiles pull request #1754
Opened 2023-03-05 21:16 UTC by AsserElfeki

resolves #1753

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-03-06 02:47 UTC, Panquesito7 requested changes

2023-03-06 02:47 UTC, Panquesito7 commented on profiles/AsserELfeki.json
> +  "image": "hhttps://user-images.githubusercontent.com/66274223/222985800-f94ad181-7030-4f69-96df-83da43221e96.png",
Wrong link.
```suggestion
  "image": "https://user-images.githubusercontent.com/66274223/222985800-f94ad181-7030-4f69-96df-83da43221e96.png",
```

2023-03-06 03:38 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-06 12:30 UTC, AsserElfeki commented
thank you :)

2023-03-06 12:34 UTC, AsserElfeki commented
will it be merged ?

2023-03-09 20:45 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-03-09 20:46 UTC, merged