fix: add srishti666
EddieHubCommunity/awesome-github-profiles pull request #1761
Opened 2023-03-20 20:17 UTC by srishti666

resolve #1768

2023-03-22 05:33 UTC, Panquesito7 requested changes
Please create a valid GitHub issue as explained in the [readme](https://github.com/EddieHubCommunity/awesome-github-profiles#how-can-i-add-my-github-profile-%EF%B8%8F%EF%B8%8F).
Let us know if you need any help with that. Thanks. 🙂

2023-03-23 17:20 UTC, srishti666 commented
I have accidentally written the wrong issue number , my correct issue number is #1768

2023-03-24 01:03 UTC, schmelto requested changes

2023-03-24 01:03 UTC, schmelto commented on profiles/srishti666.json
> +  "issueId": 1759,
```suggestion
  "issueId": 1768,
```

2023-03-24 01:04 UTC, schmelto approved these changes

2023-03-24 02:59 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-24 03:00 UTC, merged