fix: add nancyKasaudhan20
EddieHubCommunity/awesome-github-profiles pull request #1765
Opened 2023-03-22 10:34 UTC by nancyKasaudhan20

resolves #1764 

## Checklist for profile addition

- [x] Name the PR `fix: add nancyKasaudhan20`.
- [x] You've added file named `nancyKasaudhan20.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

2023-03-24 02:57 UTC, Panquesito7 requested changes

2023-03-24 02:57 UTC, Panquesito7 commented on profiles/nancyKasaudhan20.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-03-24 02:57 UTC, Panquesito7 commented on profiles/nancyKasaudhan20.json
> +    "image": "https://avatars.githubusercontent.com/u/97733705?v=4",
I recommend more of an image like this. What do you think? 🙂

![image](https://user-images.githubusercontent.com/51391473/227412755-e7b82083-a048-4026-965d-d74706dbf55a.png)

```suggestion
    "image": "https://user-images.githubusercontent.com/51391473/227412755-e7b82083-a048-4026-965d-d74706dbf55a.png",
```

2023-08-15 06:59 UTC, schmelto commented
closing due to inactivity feel free to reopen.

2023-08-15 06:59 UTC, closed without merging