add <minhaj-313>
EddieHubCommunity/awesome-github-profiles pull request #1767
Opened 2023-03-22 14:36 UTC by minhaj-313

resolves #1766 

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-03-23 03:11 UTC, PiseAtharva reviewed
Hey Minhaj, really appreciated the profile, but I think you missed the check marks in your PR (it should be similar to #1759 just for your reference )

2023-03-23 04:54 UTC, schmelto approved these changes

2023-03-23 07:20 UTC, minhaj-313 commented
> Hey Minhaj, really appreciated the profile, but I think you missed the check marks in your PR (it should be similar to #1759 just for your reference )

I Updated now accept my PR

2023-03-23 08:02 UTC, PiseAtharva commented
> I Updated now accept my PR

Tom already did that for ya 😅

2023-03-23 09:59 UTC, minhaj-313 commented
> > I Updated now accept my PR
> 
> Tom already did that for ya 😅

You guys haven't done it yet, Merge it.

2023-03-24 02:58 UTC, Panquesito7 requested changes

2023-03-24 02:58 UTC, Panquesito7 commented on profiles/minhaj-313.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-03-25 05:29 UTC, getlost01 approved these changes
Fine

2023-04-03 12:47 UTC, minhaj-313 reviewed
Please Merge my PR

2023-04-03 17:44 UTC, Pradumnasaraf requested changes
Hey,

Revert changes from another file. We don't allow modification is someone's profile.

2023-04-04 08:51 UTC, closed without merging