fix: add <Mahikolhe23> #1806
EddieHubCommunity/awesome-github-profiles pull request #1807
Opened 2023-04-17 18:13 UTC by Mahikolhe23

resolves ##1806 

## Checklist for profile addition

- [ ] Name the PR `fix: add <Mahikolhe23>`.
- [ ] You've added file named `Mahikolhe23.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-04-20 02:27 UTC, Panquesito7 requested changes

2023-04-20 02:27 UTC, Panquesito7 commented on profiles/Mahikolhe23.json
> +  "image": "https://github.com/Mahikolhe23/Mahikolhe23/blob/main/Assets/Mahi%20Git%20Profile.png",
```suggestion
  "image": "https://raw.githubusercontent.com/Mahikolhe23/Mahikolhe23/main/Assets/Mahi%20Git%20Profile.png",
```

2023-04-20 07:49 UTC, Mahikolhe23 reviewed
changes done as per requested

2023-04-20 07:49 UTC, Mahikolhe23 commented
kindly review

2023-04-20 07:53 UTC, Mahikolhe23 commented on profiles/Mahikolhe23.json
> +  "image": "https://github.com/Mahikolhe23/Mahikolhe23/blob/main/Assets/Mahi%20Git%20Profile.png",
done

2023-04-20 23:37 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-04-21 04:42 UTC, Mahikolhe23 commented
Kindly merge 🙏

2023-04-21 15:02 UTC, Panquesito7 commented
> Kindly merge 🙏

Your pull request will be merged once one or more maintainers approve the PR.

2023-04-21 17:23 UTC, Mahikolhe23 commented
> > Kindly merge 🙏
> 
> Your pull request will be merged once one or more maintainers approve the PR.
> 

Okay

2023-04-27 08:36 UTC, Pradumnasaraf approved these changes
Looks good to merge :tada:.

2023-04-27 08:36 UTC, merged

2023-04-27 08:38 UTC, Mahikolhe23 commented
Thanks