fix: add Ramzi-Abidi #1811
EddieHubCommunity/awesome-github-profiles pull request #1812
Opened 2023-04-21 19:38 UTC by Ramzi-Abidi

resolves #1811

## Checklist for profile addition

- [ ] I've added Ramzi-Abidi.json in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles)
- [ ] I've linked this PR to #1811

2023-04-21 20:17 UTC, Ramzi-Abidi commented
> ### Hey! contributor, thank you for opening a Pull Request 🎉.
> Soon one of our maintainers will review it and provide you with feedback/suggestions. Star ⭐ this repo to show us support.Happy, Open Source!

Okay, I'm waiting :))

2023-04-25 08:16 UTC, schmelto approved these changes

2023-04-26 15:05 UTC, Panquesito7 requested changes

2023-04-26 15:05 UTC, Panquesito7 commented on profiles/Ramzi-Abidi.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-04-26 15:06 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-04-26 15:06 UTC, merged