issue : 1777 arvind2602
EddieHubCommunity/awesome-github-profiles pull request #1813
Opened 2023-04-27 13:37 UTC by arvind2602

resolves #issueNumber

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-04-27 16:52 UTC, Panquesito7 requested changes

2023-04-27 16:52 UTC, Panquesito7 commented on profiles/arvind2602.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-04-28 05:10 UTC, arvind2602 commented
Done

2023-04-28 09:21 UTC, schmelto approved these changes

2023-04-28 14:30 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-04-28 14:31 UTC, merged