fix: add Bieefilled
EddieHubCommunity/awesome-github-profiles pull request #1836
Opened 2023-06-03 22:21 UTC by Petsamuel

resolves #1835

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `Bieefilled.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-06-04 15:03 UTC, Panquesito7 requested changes

2023-06-04 15:03 UTC, Panquesito7 commented on profiles/bieefilled.json
> +  "username": "Bieefilled"
I believe this should be `Petsamuel`.
```suggestion
  "username": "Petsamuel"
```

2023-06-04 15:40 UTC, Petsamuel commented on profiles/bieefilled.json
> +  "username": "Bieefilled"
I own that name too

2023-06-04 15:56 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-06-05 12:49 UTC, schmelto approved these changes

2023-06-05 12:50 UTC, merged