resolve issue 1675
EddieHubCommunity/awesome-github-profiles pull request #1842
Opened 2023-06-09 14:48 UTC by wellingtonmwadali

resolves #issueNumber

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-06-09 15:48 UTC, Panquesito7 requested changes

2023-06-09 15:48 UTC, Panquesito7 commented on profiles/wellingtonmwadali.json
> +    "image": "https://github.com/wellingtonmwadali",
Wrong image link.
```suggestion
    "image": "https://user-images.githubusercontent.com/121486233/244718177-06e063c7-96f4-4881-ac6a-ec184bdf9d0f.jpg",
```

2023-06-09 15:48 UTC, Panquesito7 commented on profiles/wellingtonmwadali.json
> +
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-08-28 11:00 UTC, schmelto commented
closing due to inactivity feel free to reopen. :)

2023-08-28 11:00 UTC, closed without merging