fix: add sabhisharma-ise
EddieHubCommunity/awesome-github-profiles pull request #1858
Opened 2023-07-02 09:47 UTC by sabhisharma-ise

closes #1856 

## Checklist for profile addition

- [X] Name the PR `fix: add <your-username>`.
- [X] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [X] You've linked the PR to the correct issue.

---

## Other additions/changes

- [X] Changes made in this PR are mentioned below
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.
- [X] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

The PR adds sabhisharma-ise.json file in profiles folder.

## Notes

2023-07-02 12:50 UTC, schmelto commented on profiles/sabhisharma-ise.json
> +  }
```suggestion
}

```

2023-07-03 16:52 UTC, Panquesito7 requested changes

2023-07-03 16:52 UTC, Panquesito7 commented on profiles/sabhisharma-ise.json
> +    "image": "![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/100849696/7a94a885-6d68-480a-b81c-e1860e63909c)",
Only the URL must be provided, and not in Markdown format.
```suggestion
    "image": "https://github.com/EddieHubCommunity/awesome-github-profiles/assets/100849696/7a94a885-6d68-480a-b81c-e1860e63909c",
```

2023-07-03 19:39 UTC, schmelto approved these changes

2023-07-03 21:57 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-07-03 21:58 UTC, merged