Manzil infinity180 patch 1 broken badge
EddieHubCommunity/awesome-github-profiles pull request #1904
Opened 2023-08-28 14:34 UTC by manzil-infinity180

closes #1901 

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2023-08-28 15:29 UTC, schmelto requested changes
<img width="292" alt="image" src="https://github.com/EddieHubCommunity/awesome-github-profiles/assets/30869493/aa6b1686-8876-4eaf-bcdc-2182551be7ac">

this doesn't look quite right yet

2023-08-28 15:47 UTC, manzil-infinity180 reviewed
What i think i can change with shields.io i changed... I think now it look better than previous

2023-08-28 18:16 UTC, schmelto commented
![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/30869493/19794090-c1d5-464b-abc8-d3ac448bca3b)

2023-08-29 07:02 UTC, schmelto commented on README.md
> +    <img src="https://img.shields.io/badge/open-source-love" alt="open source badge" />
```suggestion
    <img src="https://img.shields.io/badge/open-source-green" alt="open source badge" />
```

2023-08-29 07:02 UTC, schmelto commented on README.md
> +    <img src="https://img.shields.io/badge/check-it_out-love" alt="check it out badge" />
```suggestion
    <img src="https://img.shields.io/badge/check_it-out-blue" alt="check it out badge" />
```

2023-08-29 07:02 UTC, schmelto commented on README.md
> +    <img src="https://img.shields.io/badge/built-by_developers-blue" alt="built by developers badge" />
```suggestion
    <img src="https://img.shields.io/badge/built_by-developers-yellow" alt="built by developers badge" />
```

2023-08-29 11:29 UTC, manzil-infinity180 commented
> ![image](https://user-images.githubusercontent.com/30869493/263786983-19794090-c1d5-464b-abc8-d3ac448bca3b.png)
> 
> Doesn't seem right they're should be like 'made with love' etc

Sir if you satisfied with the change Please merge it

2023-08-29 11:36 UTC, schmelto approved these changes

2023-08-29 11:37 UTC, merged