Rachit Tandon
EddieHubCommunity/awesome-github-profiles pull request #296
Opened 2021-01-31 19:01 UTC by webdevrachit

![Screenshot (14)](https://user-images.githubusercontent.com/72686780/106394857-daf4ab00-6424-11eb-80c0-f069fcb715e4.png)

2021-02-01 01:23 UTC, w3bdesign requested changes
Needs a } at the end

2021-02-02 04:30 UTC, AllanRegush commented on data.json
> +    "issueNumber": 295
Looks like there is a missing closing bracket `}`

2021-02-02 04:30 UTC, AllanRegush reviewed
Looking Good :+1: Just a minor adjustment. :nerd_face:

2021-02-02 04:36 UTC, AllanRegush commented
Merged #290, Thank you for the PR :+1:  - this is a duplicate PR, Closing :nerd_face:

2021-02-02 04:36 UTC, closed without merging