update data.json (#310)
EddieHubCommunity/awesome-github-profiles pull request #311
Opened 2021-02-02 09:11 UTC by An-prog-hub

![An-prog-hub](https://user-images.githubusercontent.com/67872399/106577647-9f60fa80-6564-11eb-86f4-e1ecff9772f8.png)

2021-02-02 18:21 UTC, AllanRegush commented on data.json
> +  },
I don't think we need a comma here. :nerd_face:

2021-02-02 18:22 UTC, AllanRegush reviewed
Looking Good :+1: Just a minor adjustment :smile:

2021-02-06 04:31 UTC, AllanRegush commented
@An-prog-hub Just Checking in. Do you need any help? If so, let me know :nerd_face:

2021-03-02 18:22 UTC, AllanRegush commented
@An-prog-hub Just Checking in again. Do you need any help? If so, let me know 🤓

2021-03-04 06:07 UTC, Vyvy-vi requested changes

2021-03-04 06:07 UTC, Vyvy-vi commented on data.json
> +  },
```suggestion
  }
```

2021-03-04 06:07 UTC, Vyvy-vi commented on data.json
> +  },
As Allan said, the comma could be removed 🤓 (I think that should fix the prettier fails)

2021-03-10 02:17 UTC, AllanRegush approved these changes
Looks Good :+1:

2021-03-10 02:23 UTC, merged