Added Profile Readme details in data.json
EddieHubCommunity/awesome-github-profiles pull request #346
Opened 2021-02-07 05:36 UTC by smv1999

2021-02-07 15:53 UTC, Nitesh-thapliyal reviewed
## Image URL must be of the ss uploaded in the Issue.

> To add your github profile
- create an issue, with the title as your name, and in the description put a screenshot of the customized GitHub profile page and then copy the link and that link you have to use in data.json .

2021-02-08 03:11 UTC, AllanRegush reviewed
Looking Good 👍 Just a minor adjustment 🤓

2021-02-08 03:11 UTC, AllanRegush commented on data.json
> +    "imageUrl": "https://drive.google.com/file/d/1YaiFeRqbPNzxNON3UjtPXaqiCmuNErXD/view?usp=sharing",
Please paste your image into your issue message. It will give you a link to put in here 👍

2021-02-08 05:59 UTC, smv1999 commented
@AllanRegush @Nitesh-thapliyal I have made the suggested changes.

2021-02-08 06:20 UTC, Nitesh-thapliyal approved these changes
Looks good👍Thank's for adding your profile🙌

2021-02-08 23:27 UTC, AllanRegush approved these changes
Looks Good :+1: Thank you

2021-02-08 23:27 UTC, AllanRegush commented
It looks like there is a conflict could you resolve this? If you need any help let me know. :nerd_face:

2021-02-09 05:28 UTC, smv1999 commented
I guess it is fine now @AllanRegush .

2021-02-09 18:19 UTC, AllanRegush commented
It looks like someones entry got over ridden. If you need any help let me know :nerd_face:

2021-02-09 18:21 UTC, AllanRegush requested changes
It looks like  in the conflict someones entry got overridden.

2021-02-10 13:38 UTC, smv1999 commented
Really sorry about that @AllanRegush . I have created a new PR  #356  for the same as I faced some issues.

2021-02-10 13:38 UTC, closed without merging