add pulkit0076
EddieHubCommunity/awesome-github-profiles pull request #370
Opened 2021-02-15 03:39 UTC by Pulkit0076

resolve #368

2021-02-18 00:51 UTC, AllanRegush reviewed
Looking Good 👍

2021-02-18 00:51 UTC, AllanRegush commented on data.json
> +    "name": "Pulkit Singh",
Thank you for your PR 👍 Could you move your entry to the end?

2021-03-02 18:23 UTC, AllanRegush commented
@PulkitSinghDev Just checking in. Do you need any help? If you do let us know 🤓

2021-03-03 02:53 UTC, PulkitSinghDev commented
> @PulkitSinghDev Just checking in. Do you need any help? If you do let us know 🤓
Yeah sure will let you know, if I want any help 😄

2021-03-30 05:20 UTC, AllanRegush commented
Hi @PulkitSinghDev Just Checking in. Do you need any help? I'd love to have this PR Merged :nerd_face:

2021-05-06 15:36 UTC, Vyvy-vi requested changes
Hey, @PulkitSinghDev 
Do you need any help/context on the suggestions?

2021-06-14 14:16 UTC, schmelto commented
@PulkitSinghDev just checking in

2021-07-29 09:07 UTC, schmelto commented
He, due to long inactivity I will close this PR now. Feel free to reopen it and make the necessary changes or create a new one. Thanks!

2021-07-29 09:07 UTC, closed without merging