add your-HenokB
EddieHubCommunity/awesome-github-profiles pull request #372
Opened 2021-02-15 17:00 UTC by HenokB

resolve #371

2021-02-16 13:47 UTC, schmelto requested changes

2021-02-16 13:47 UTC, schmelto commented on data.json
>    }
You should at a `, ` here I think

2021-02-17 23:22 UTC, eddiejaoude commented on data.json
>    }
Thank you for reviewing @schmelto 👍

2021-02-18 00:53 UTC, AllanRegush reviewed
Looking Good 👍

2021-02-18 00:53 UTC, AllanRegush commented on data.json
> +    "issueNumber": 351
What is your Issue number? #351 is a PR

2021-03-02 18:24 UTC, AllanRegush commented
@HenokB Just Checking in. Do you need any help? If you do let us know 🤓

2021-03-04 06:10 UTC, Vyvy-vi commented on data.json
> +    "issueNumber": 351
I think their issue is #371

2021-03-15 11:12 UTC, praveenscience requested changes
Correct your issue number and please fix the error on the code.
![image](https://user-images.githubusercontent.com/1830380/111144942-a3c6fd00-857f-11eb-80cb-f3f609680b74.png)

2021-03-30 05:19 UTC, AllanRegush commented
Hi @HenokB Just Checking in. If you need any help let use know :nerd_face:

2021-06-14 14:27 UTC, schmelto requested changes

2021-06-14 14:27 UTC, schmelto commented on data.json
>    }
```suggestion
  },
```

2021-06-14 14:27 UTC, schmelto commented on data.json
> +    "issueNumber": 351
```suggestion
    "issueNumber": 371
```

2021-07-29 09:14 UTC, schmelto approved these changes

2021-07-29 09:21 UTC, merged

2021-07-29 17:54 UTC, Panquesito7 commented on data.json
> +    "name": "Henok B Ademtew",
I copied their name from their GitHub bio, and I think it'd be better.

```suggestion
    "name": "Henok Biadglign Ademtew",
```

Or

```suggestion
    "name": "Henok B. Ademtew",
```

too.