add pvcodes
EddieHubCommunity/awesome-github-profiles pull request #400
Opened 2021-03-19 09:54 UTC by pvcodes

Hi, here is my first PR on EddieHubCommunity, looking forward for more of the.
resolve #399

2021-03-19 11:05 UTC, schmelto approved these changes

2021-03-19 22:45 UTC, AllanRegush requested changes
Looking Good :+1: Just a small adjustment :nerd_face:

2021-03-19 22:45 UTC, AllanRegush commented on data.json
> +    "imageUrl": "https://avatars3.githubusercontent.com/pvcodes",
This shouldn't be your user avatar it should be an image of your profile
```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/54075838/111760905-40153a80-88c5-11eb-9600-aa49a78ddd05.png",
```

2021-03-20 03:59 UTC, pvcodes commented
> Looking Good :+1: Just a small adjustment :nerd_face: 

Yup, I committed that too.

2021-03-22 02:01 UTC, AllanRegush approved these changes
Looks Good :+1:

2021-03-22 02:02 UTC, AllanRegush commented
Looks like there is a conflict would you be able to fix it? If you need any help let us know :nerd_face:

2021-03-22 03:52 UTC, pvcodes commented
Hi, @AllanRegush which conflict.

2021-03-22 14:33 UTC, AllanRegush commented
![Screenshot_20210322_082822](https://user-images.githubusercontent.com/17693494/112006142-0f154f80-8ae9-11eb-848e-52067cddfc74.png)

Here is some  [documantation](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github) on resolving conflicts.

2021-03-30 05:18 UTC, AllanRegush approved these changes

2021-03-30 05:18 UTC, merged