Add Tarun-Kamboj
EddieHubCommunity/awesome-github-profiles pull request #420
Opened 2021-03-28 07:20 UTC by Tarun-Kamboj

Resolve #419

2021-03-29 16:44 UTC, vikkastiwari commented
It seems great to me ;)

2021-03-30 05:04 UTC, AllanRegush reviewed
Looking Good :+1: Just a minor adjustment. :nerd_face:

2021-03-30 05:04 UTC, AllanRegush commented on data.json
> +  {
Please add yourself to the bottom :smile:

2021-03-30 11:47 UTC, Tarun-Kamboj commented
@AllanRegush is it ok now?

2021-03-30 15:24 UTC, galahad42 approved these changes

2021-03-31 12:10 UTC, schmelto requested changes
Think what @AllanRegush ment was right at the end of the document (Line 697)

2021-04-02 15:38 UTC, AllanRegush commented on data.json
> +  {
Please add yourself to the end of the `data.json1 file.

2021-04-02 15:38 UTC, AllanRegush requested changes
Looking Good :+1: Just a minor adjustment. :nerd_face:

2021-04-03 07:16 UTC, Tarun-Kamboj commented
Requested changes done. @AllanRegush

2021-04-04 10:56 UTC, schmelto approved these changes

2021-04-05 12:32 UTC, AllanRegush approved these changes
Looks Good :+1: Thank you :smile:

2021-04-05 12:33 UTC, merged