add rudrabarad
EddieHubCommunity/awesome-github-profiles pull request #441
Opened 2021-04-19 19:50 UTC by rudrabarad

resolve #440

2021-04-19 20:01 UTC, schmelto approved these changes

2021-04-20 23:32 UTC, AllanRegush approved these changes
Looks Good :+1: Thank you :smile:

2021-04-20 23:32 UTC, AllanRegush commented
Thanks for reviewing @schmelto

2021-04-20 23:33 UTC, AllanRegush commented
@rudrabarad Looks like there is a merge conflict. Could you resolve this? If you need any help let us know :nerd_face:

2021-04-21 07:54 UTC, rudrabarad commented
> @rudrabarad Looks like there is a merge conflict. Could you resolve this? If you need any help let us know

I've successfully resolved the conflict @AllanRegush  ✅

2021-04-21 08:13 UTC, schmelto requested changes
maybe a small improvement

2021-04-21 08:13 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-04-21 08:13 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-04-21 08:39 UTC, rudrabarad commented
Can you check now? @AllanRegush 😅

2021-04-21 09:01 UTC, schmelto approved these changes

2021-05-01 13:45 UTC, merged