rishabhrathore055
EddieHubCommunity/awesome-github-profiles pull request #446
Opened 2021-04-20 16:09 UTC by rishabhrathore055

#445

2021-04-20 16:26 UTC, schmelto requested changes
can you change the description from #445 to resolve #445 or fixes #445 that the issue is automatically closed on PR merge 🚀

2021-04-20 16:26 UTC, schmelto commented on data.json
> +   {
```suggestion
  {
```
please make this line up with the other braces

2021-04-20 16:26 UTC, schmelto commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/77366500/115426452-234e8880-a21e-11eb-9e2d-c508acdb921f.jp",
take a look at your image link there is a missing `p` for `jpg`.

```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/77366500/115426452-234e8880-a21e-11eb-9e2d-c508acdb921f.jpg",
```

2021-04-20 16:45 UTC, schmelto approved these changes
LGTM

2021-04-20 23:28 UTC, AllanRegush approved these changes
Looks Good :+1: Thank you :smile:

2021-04-20 23:29 UTC, AllanRegush commented
Thanks for reviewing @schmelto

2021-04-20 23:29 UTC, merged

2021-04-21 03:26 UTC, rishabhrathore055 commented
ThankYou So Much

On Wed, 21 Apr 2021, 4:59 am Allan Regush, ***@***.***> wrote:

> *@AllanRegush* approved this pull request.
>
> Looks Good 👍 Thank you 😄
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/446#pullrequestreview-640507096>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASOIJZESWTFOPJALEYTYLZDTJYE4HANCNFSM43IPH3EA>
> .
>