Add advaith-unnikrishnan
EddieHubCommunity/awesome-github-profiles pull request #448
Opened 2021-04-21 05:06 UTC by advaith-unnikrishnan

resolve #447

2021-04-21 08:03 UTC, schmelto requested changes

2021-04-21 08:03 UTC, schmelto commented on data.json
> +}
please line up with the other braces
```suggestion
  }
```

2021-04-21 09:02 UTC, schmelto approved these changes

2021-05-01 13:53 UTC, schmelto commented
@advaith-unnikrishnan looks like there is a merge conflict. Could you resolve this? If you need any help please let us know 🚀

2021-05-01 14:41 UTC, advaith-unnikrishnan commented
@schmelto  I have resolved the conflict

2021-05-01 14:42 UTC, schmelto approved these changes

2021-05-01 14:42 UTC, merged