add Yaseen549
EddieHubCommunity/awesome-github-profiles pull request #450
Opened 2021-04-21 12:08 UTC by Yaseen549

resolve #449

2021-04-21 12:51 UTC, schmelto requested changes

2021-04-21 12:51 UTC, schmelto commented on data.json
> +}
```suggestion
  }
```
Line this up with the other curly braces

2021-04-21 12:51 UTC, schmelto commented on data.json
>    }
```suggestion
  },
```
Here is a `,` missing

2021-04-21 13:07 UTC, Yaseen549 reviewed
Solved

2021-04-21 13:07 UTC, Yaseen549 commented on data.json
>    }
Got it!

2021-04-21 13:10 UTC, Yaseen549 reviewed
Added comma "," and removed "," after my data "},"

2021-04-21 13:29 UTC, schmelto approved these changes

2021-04-25 18:27 UTC, srinath1412001 approved these changes

2021-05-01 13:54 UTC, schmelto commented
Hey @Yaseen549 looks like there is a merge conflict. Could you resolve this? If you need any help feel free to ask 🚀

2021-05-01 13:59 UTC, Yaseen549 commented
> Hey @Yaseen549 looks like there is a merge conflict. Could you resolve this? If you need any help feel free to ask 🚀

Hi, Thank you for informing me, but am quite new to contributing so, I don't know that much, I'll take back this commit, if it makes any problem to the repo.

2021-05-01 14:21 UTC, schmelto commented
@Yaseen549 you don't have to close the pr. Resolving a merge conflict is no magic. You just have to pull the latest changes from this repository to your fork and then it will show you the conflicting lines. Then you can just resolve them. If you don't feel comfortable with this (you can reopen this PR) and I will solve the conflicts for you 😄

2021-05-01 14:24 UTC, Yaseen549 commented
> @Yaseen549 you don't have to close the pr. Resolving a merge conflict is no magic. You just have to pull the latest changes from this repository to your fork and then it will show you the conflicting lines. Then you can just resolve them. If you don't feel comfortable with this (you can reopen this PR) and I will solve the conflicts for you 😄

Thank you so much

2021-05-01 14:29 UTC, schmelto commented
@Yaseen549 would you like to try resolving the conflict by your own or should I resolve the conflict?

2021-05-01 14:34 UTC, Yaseen549 commented
> @Yaseen549 would you like to try resolving the conflict by your own or should I resolve the conflict?

Can you please do this for me?

2021-05-01 14:38 UTC, merged

2021-05-01 14:40 UTC, schmelto commented
@Yaseen549 done 🚀 you should find your profile nearly at the end of the readme now 👍🏼

2021-05-01 14:44 UTC, Yaseen549 commented
Thank you so much @schmelto, got it!

2021-05-01 14:46 UTC, schmelto commented
> Thank you so much @schmelto, got it!

No problem! Nice GitHub Profile btw