add saswatsamal
EddieHubCommunity/awesome-github-profiles pull request #463
Opened 2021-04-26 12:00 UTC by saswatsamal

resolve #462

2021-04-26 15:03 UTC, schmelto requested changes

2021-04-26 15:03 UTC, schmelto commented on data.json
> +    {
```suggestion
  {
```
line up with the other brace

2021-04-26 16:41 UTC, schmelto approved these changes

2021-04-28 18:27 UTC, srinath1412001 approved these changes

2021-04-28 23:56 UTC, AllanRegush approved these changes
Looks Good :+1: Thank you

2021-04-28 23:56 UTC, AllanRegush commented
Thanks @schmelto and @srinath1412001 for reviewing.

2021-04-28 23:57 UTC, merged