add harikanani profile
EddieHubCommunity/awesome-github-profiles pull request #470
Opened 2021-05-04 04:04 UTC by harikanani

2021-05-04 05:10 UTC, schmelto requested changes
Looking good so far. Maybe one little change 😄

2021-05-04 05:10 UTC, schmelto commented on data.json
> +  },
```suggestion
  }
```

2021-05-04 06:14 UTC, harikanani reviewed
i have done all requested changes

2021-05-04 09:15 UTC, harikanani reviewed
resolved issue

2021-05-04 12:28 UTC, schmelto commented
@AllanRegush do you know why the Linter is failing?

2021-05-04 12:30 UTC, schmelto approved these changes
PR is looking good for me. I wait for @AllanRegush maybe he or someone else got an idea because of the failing Linter

2021-05-05 03:39 UTC, harikanani commented
> @AllanRegush do you know why the Linter is failing?

No i don't know why it's failing but I think now it's looks fine! Let's wait for @AllanRegush review.

2021-05-05 11:20 UTC, schmelto commented
> No i don't know why it's failing but I think now it's looks fine! Let's wait for @AllanRegush review.

I've opened a PR for this on #478 but dont know where the linter error comes from.

2021-05-05 17:12 UTC, merged

2021-05-05 17:13 UTC, schmelto commented
prettier was fixed I merged the PR thanks for the patience 🚀