Add SulthanNK
EddieHubCommunity/awesome-github-profiles pull request #483
Opened 2021-05-08 17:02 UTC by SulthanNK

resolve #482

2021-05-08 19:43 UTC, schmelto requested changes

2021-05-08 19:43 UTC, schmelto commented on data.json
> +}
```suggestion
  }
```
Lining up with the other braces

2021-05-09 04:30 UTC, SulthanNK commented on data.json
> +}
Added the request changes in the file.

2021-05-09 11:21 UTC, schmelto approved these changes

2021-05-09 11:22 UTC, merged