add thejaswin123
EddieHubCommunity/awesome-github-profiles pull request #508
Opened 2021-05-14 17:16 UTC by thejaswin123

resolve #507

2021-05-14 17:40 UTC, starlightknown requested changes
remove the extra line and align the bracket

2021-05-14 17:40 UTC, starlightknown commented on data.json
> +}
```suggestion
    }
```

2021-05-14 17:40 UTC, starlightknown commented on data.json
> +
```suggestion

```

2021-05-14 21:17 UTC, schmelto requested changes
Please resolve the issues / suggestions from @starlightknown otherwise it looks good for me

2021-05-15 02:52 UTC, thejaswin123 commented
> remove the extra line and align the bracket

removed the extra lines and aligned the brackets

2021-05-15 02:53 UTC, thejaswin123 commented
> Please resolve the issues / suggestions from @starlightknown otherwise it looks good for me

resolved

2021-05-15 02:59 UTC, starlightknown approved these changes
LGTM 👍🏼

2021-05-15 03:02 UTC, deephunt3r approved these changes

2021-05-15 07:00 UTC, schmelto approved these changes

2021-05-15 07:00 UTC, merged

2021-05-15 07:02 UTC, schmelto commented
Thanks @starlightknown and @deephunt3r for reviewing 🚀