Gagan3012
EddieHubCommunity/awesome-github-profiles pull request #540
Opened 2021-06-01 17:20 UTC by gagan3012

![image](https://user-images.githubusercontent.com/49101362/120365112-e4066380-c2c2-11eb-90f9-1d283c915e3f.png)

2021-06-01 17:21 UTC, gagan3012 commented on data.json
> +  },
Remove this comma

2021-06-01 17:53 UTC, schmelto requested changes

2021-06-01 17:53 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-06-01 17:53 UTC, schmelto commented on data.json
> +  },
```suggestion
  }
```

2021-06-01 17:53 UTC, schmelto commented
Could you also add `resolve #yourissuenumber ` to the pr description?

2021-06-01 18:12 UTC, closed without merging

2021-07-02 23:45 UTC, eddiejaoude commented
Did you mean to close this @gagan3012 ?

2021-07-02 23:45 UTC, eddiejaoude commented
Oh I see there is another PR https://github.com/EddieHubCommunity/awesome-github-profiles/pull/541