add leticiarosario
EddieHubCommunity/awesome-github-profiles pull request #556
Opened 2021-06-16 18:28 UTC by Leticiarosario

resolve #554

2021-06-16 18:42 UTC, starlightknown requested changes
Other than this small change, it's good. Also please close the other PR #555

2021-06-16 18:42 UTC, starlightknown commented on data.json
>    }
```suggestion
  },
```

2021-06-16 20:32 UTC, schmelto commented on data.json
>    }
With this change it looking good for me

2021-06-17 06:13 UTC, schmelto commented
duplicate with #555 and #557

2021-07-23 11:20 UTC, MRslimcoder approved these changes
LGTM

2021-07-23 11:45 UTC, schmelto requested changes

2021-07-23 11:45 UTC, schmelto commented on data.json
>    }
```suggestion
   },
```

2021-07-23 11:46 UTC, schmelto commented on data.json
> +   },
```suggestion
  },
```

2021-07-23 11:48 UTC, schmelto approved these changes

2021-07-23 11:48 UTC, merged