add sonichigo
EddieHubCommunity/awesome-github-profiles pull request #585
Opened 2021-07-10 16:30 UTC by Sonichigo

resolve #584

2021-07-10 16:49 UTC, kaiwalyakoparkar approved these changes
LGTM :rocket: Thanks for collaborating and contributing

2021-07-10 18:30 UTC, schmelto requested changes

2021-07-10 18:30 UTC, schmelto commented on data.json
> +    {
Those should align with the other brackets

2021-07-11 03:02 UTC, Sonichigo reviewed
Done please check!!

2021-07-11 06:27 UTC, schmelto approved these changes
Lgtm

2021-07-11 06:28 UTC, schmelto commented
Currnelty in Holliday but I have to check why the action is failing. Or someone else could do this :D

2021-07-11 12:02 UTC, Sonichigo commented
This happened after aligning the brackets only! I guess at some point there is no alignment!

2021-07-12 13:10 UTC, merged