add hippyaki
EddieHubCommunity/awesome-github-profiles pull request #587
Opened 2021-07-11 14:37 UTC by hippyaki

resolve #586

2021-07-11 15:01 UTC, deephunt3r approved these changes
LGTM 🚀

2021-07-11 17:10 UTC, schmelto requested changes

2021-07-11 17:10 UTC, schmelto commented on data.json
>    }
```suggestion
   }, 
```

2021-07-12 01:17 UTC, Panquesito7 commented on data.json
>    }
```suggestion
  },
```

2021-07-12 04:42 UTC, hippyaki commented
Changes made.

2021-07-12 05:06 UTC, Panquesito7 approved these changes
Looks good. Thank you for your contribution! We hope you keep contributing with us! 😉 👍

2021-07-12 13:12 UTC, schmelto approved these changes

2021-07-12 13:12 UTC, merged