Add victoria-lo
EddieHubCommunity/awesome-github-profiles pull request #591
Opened 2021-07-15 14:51 UTC by victoria-lo

Resolve #590

2021-07-15 15:24 UTC, schmelto requested changes
Please add yourself at the end of the data.json file

2021-07-15 18:50 UTC, Panquesito7 reviewed
I think you should re-open the #590 issue. It should be closed once this PR is merged.

2021-07-16 03:34 UTC, victoria-lo commented
I have reopened the issue and add myself at the end of data.json. Thanks :)

2021-07-16 05:50 UTC, schmelto requested changes

2021-07-16 05:50 UTC, schmelto commented on data.json
> +    "imageUrl":"https://user-images.githubusercontent.com/47699978/125807703-6d8c6adf-d642-42f2-b1bf-51f6a32c0a84.png"
```suggestion
    "imageUrl":"https://user-images.githubusercontent.com/47699978/125807703-6d8c6adf-d642-42f2-b1bf-51f6a32c0a84.png", 
```

2021-07-16 07:06 UTC, rahmanharoon requested changes

2021-07-16 07:06 UTC, rahmanharoon commented on data.json
> +    "imageUrl":"https://user-images.githubusercontent.com/47699978/125807703-6d8c6adf-d642-42f2-b1bf-51f6a32c0a84.png",
```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/47699978/125807703-6d8c6adf-d642-42f2-b1bf-51f6a32c0a84.png", 
```

2021-07-16 08:00 UTC, schmelto approved these changes
lgtm

2021-07-16 08:01 UTC, merged

2021-07-16 08:01 UTC, schmelto commented
Thanks for your contribution and collaboration 🚀