Add MrSlimCoder
EddieHubCommunity/awesome-github-profiles pull request #609
Opened 2021-07-19 20:14 UTC by MRslimcoder

#607

2021-07-19 20:19 UTC, Panquesito7 approved these changes
LGTM. Thank you for your contribution! 😄:+1:
I would only suggest adding `Resolve` in your comment before the issue number.

2021-07-19 20:44 UTC, schmelto requested changes

2021-07-19 20:44 UTC, schmelto commented on data.json
> +}
```suggestion
  }
```

2021-07-20 11:18 UTC, MRslimcoder commented
Team, test is still failed can you please verify it' related to linting issue @schmelto @Panquesito7

2021-07-20 11:29 UTC, schmelto approved these changes
lgtm

2021-07-20 11:47 UTC, schmelto commented
> Team, test is still failed can you please verify it' related to linting issue @schmelto @Panquesito7 

I check the action issue later

2021-07-20 17:32 UTC, Panquesito7 approved these changes
LGTM. Thank you! 😄👍

2021-07-20 17:42 UTC, kaiwalyakoparkar approved these changes
LGTM :rocket: Thanks for collaborating and contributing :)

2021-07-20 17:42 UTC, merged