SahityaRoy Update data.json
EddieHubCommunity/awesome-github-profiles pull request #622
Opened 2021-07-28 12:53 UTC by SahityaRoy

2021-07-28 13:02 UTC, AvidCoder101 requested changes
@SahityaRoy Just one change, could you please add an image of your Github profile README.md into the `imageUrl`? I'll also let the admins do their reviewing. Thanks (:

2021-07-28 13:14 UTC, SahityaRoy commented
Hey i don't know how to add screenshot on issue section

On Wed, Jul 28, 2021 at 6:32 PM AvidCoder ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @SahityaRoy <https://github.com/SahityaRoy> Just one change, could you
> please add an image of your README.md into the imageUrl? I'll also let
> the admins do their reviewing. Thanks (:
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/622#pullrequestreview-716970767>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARLSWZEWZQGMFDJXJYOT27TTZ75X3ANCNFSM5BEJTUQQ>
> .
>

2021-07-28 14:45 UTC, schmelto requested changes

2021-07-28 14:45 UTC, schmelto commented
> Hey i don't know how to add screenshot on issue section

Just make a screenshot of your github profile and paste it into the description field of the issue (#621)

2021-07-29 08:58 UTC, SahityaRoy commented
![29 07 2021_14 26 39_REC](https://user-images.githubusercontent.com/72821604/127463309-7f3dc638-b2fd-4237-ab93-744a48ceb13c.png)

2021-07-29 09:00 UTC, SahityaRoy commented
done

2021-07-29 09:01 UTC, schmelto requested changes

2021-07-29 09:01 UTC, schmelto commented on data.json
> +    "imageUrl": "https://media-exp1.licdn.com/dms/image/C5603AQEYBGYcnAE7Ug/profile-displayphoto-shrink_400_400/0/1624942139886?e=1632960000&v=beta&t=ZWCRX9YfHKDGkLQVDWYkYsnWqnfbdO2r_-tCN_hb9BA",
```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/72821604/127463309-7f3dc638-b2fd-4237-ab93-744a48ceb13c.png",
```

2021-07-29 09:39 UTC, closed without merging