added Ritwik880
EddieHubCommunity/awesome-github-profiles pull request #628
Opened 2021-07-29 14:28 UTC by Ritwik880

2021-07-29 15:42 UTC, schmelto approved these changes

2021-07-29 17:50 UTC, Panquesito7 requested changes

2021-07-29 17:50 UTC, Panquesito7 commented on data.json
> +    "issueNumber": 621
Wrong issue number.

```suggestion
    "issueNumber": 627
```

2021-07-29 17:57 UTC, Ritwik880 commented
Hey @Panquesito7 now I have updated.

2021-07-29 18:05 UTC, Panquesito7 approved these changes
Looks good. Thanks! 😄

2021-07-29 20:49 UTC, w3bdesign approved these changes

2021-07-29 21:27 UTC, schmelto commented on data.json
> +    "issueNumber": 621
Good catch!

2021-07-29 21:28 UTC, schmelto commented
Hey @Ritwik880 could you resolve the merge conflict. If you need any halp please let us know.

2021-07-30 03:04 UTC, Ritwik880 commented
Hey @schmelto I think now everything is fine, please have a look.

2021-07-30 05:34 UTC, schmelto requested changes

2021-07-30 05:34 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-07-30 05:34 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-07-30 05:53 UTC, schmelto requested changes

2021-07-30 05:53 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-07-30 05:54 UTC, schmelto commented
Those tree empty lines should not be there

2021-08-01 07:22 UTC, Ritwik880 commented
Hey @schmelto I am not getting your point??

![Screenshot (348)](https://user-images.githubusercontent.com/54446880/127762822-3afc553c-39d5-4a09-9277-0f2f226b53ec.png)

2021-08-01 11:11 UTC, schmelto commented
Line 1214
Line 1208

Those you can remove due those are empty

2021-08-01 11:17 UTC, Ritwik880 commented
Hey @schmelto I think now its fine.

2021-08-01 11:59 UTC, AvidCoder101 approved these changes
LGTM @schmelto or @kaiwalyakoparkar this PR can be merged I think

2021-08-01 14:15 UTC, Panquesito7 approved these changes

2021-08-01 15:03 UTC, kaiwalyakoparkar approved these changes
LGTM :rocket: Thanks for your collaboration and contribution

2021-08-01 15:04 UTC, merged