add iamgunjan
EddieHubCommunity/awesome-github-profiles pull request #643
Opened 2021-08-11 19:58 UTC by iamgunjan

resolve #issue642

2021-08-11 20:00 UTC, AvidCoder101 requested changes

2021-08-11 20:14 UTC, schmelto commented on data.json
>  ]
The `] ` is right the but there is an additional missing `} ` closing tag

2021-08-11 20:15 UTC, schmelto requested changes

2021-08-11 20:15 UTC, schmelto commented on data.json
> +    "issueNumber": 642
```suggestion
    "issueNumber": 642
  }
```
I think it should look something like this

2021-08-11 20:16 UTC, Panquesito7 requested changes

2021-08-12 14:34 UTC, schmelto requested changes

2021-08-12 14:34 UTC, schmelto commented on data.json
> +  },
```suggestion
  }
```

2021-08-12 15:38 UTC, schmelto approved these changes

2021-08-12 15:38 UTC, merged

2021-08-12 15:46 UTC, schmelto commented
Thanks for your contribution 🚀