Update data.json
EddieHubCommunity/awesome-github-profiles pull request #644
Opened 2021-08-12 19:56 UTC by VasudevJaiswal

Add my profile data

2021-08-12 20:01 UTC, Panquesito7 requested changes

2021-08-12 20:01 UTC, Panquesito7 commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/53567221/129094169-e012e3fb-3ba9-47e7-9173-0e09e7517034.png",
Wrong URL image.
```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/85981735/129255772-5bac726e-d98e-4eb4-8c9f-c2206b72c976.png",
```

2021-08-12 22:13 UTC, schmelto requested changes
Please see @Panquesito7 comment [here](https://github.com/EddieHubCommunity/awesome-github-profiles/pull/644#discussion_r688045572 )

2021-08-12 22:14 UTC, schmelto commented
I've linked the issue #641 in the pr description thus it will automatically gets closed on pr merge.

2021-08-13 01:12 UTC, VasudevJaiswal commented
Problem Resolved 😊 
Thanks @Panquesito7

2021-08-13 03:17 UTC, Panquesito7 approved these changes
LGTM. Thank you for your contribution! 😄👍🎉
@schmelto, this PR can be merged. 👍

2021-08-13 03:19 UTC, Panquesito7 requested changes
LGTM. Thank you for your contribution! 😄👍🎉
@schmelto, this PR can be merged. 👍

2021-08-13 03:19 UTC, Panquesito7 commented on data.json
>    }
Oh, you forgot a comma here.
```suggestion
  },
```

2021-08-13 06:12 UTC, schmelto approved these changes
Lgtm

2021-08-13 06:12 UTC, merged