add your -username
EddieHubCommunity/awesome-github-profiles pull request #711
Opened 2021-09-09 06:57 UTC by Omkar0114

resolves #710

2021-09-09 09:17 UTC, schmelto requested changes

2021-09-09 09:17 UTC, schmelto commented on data.json
> +  "imageUrl": "https://www.dropbox.com/s/6myquj7ck6gflr2/Screenshot%202021-09-09%2012.07.50.png?dl=0",
please use a github image link here instead of a dropbox link. you can create it by simply pasting a screenshot of your profile in your issue

2021-09-09 10:56 UTC, schmelto requested changes
Just saw that your GitHub Profile doesnt have a custome github profile. I recomend adding a profile readme first and than subbmit your profile for awsome github profiles / adjusting the screesnhot again :)
[here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme) is a documentation for the profile readme

2021-09-10 02:02 UTC, Panquesito7 requested changes
Please see the comment above. 🙂

2021-09-11 17:38 UTC, CodingSpecies commented
@Omkar0114 to fill this pull request, you need to have a repo called: `Omkar0114/omkar0114`. There, you have a `README.md`. In the readme, write about yourself and commit your changes. Now you have a readme! If you want examples, just press our profiles avatars, and you will see our readme profiles there.
After just do this:

### What to do:

- [x] Take a screenshot of your profile, up to where it says `pinned repos`.
- [x] As you just took a screenshot, just `ctrl v` it into the issue. Or, save it to your computer and then upload it to GitHub, and it will generate a custom image URL, when you copy image address.
- [x] Go to your forked copy of the repo, and go to `data.json` and add your name, paste in the image url and fill out the rest.
### Now, just open a pull request with your changes!  🎉

Hope that helps, anymore questions feel free to ask. Thanks

2021-09-14 11:34 UTC, Omkar0114 commented
okay I'm doing now

2021-09-14 11:45 UTC, schmelto commented on data.json
> +  "issueNumber": 710
also please take a look at the spacing

```suggestion
    "name": "Omkar Kulkarni",
    "githubUsername": "Omkar0114",
    "imageUrl": "https://user-images.githubusercontent.com/88308267/132665808-d55d32e9-a79c-4c7f-8932-0f20c9442a6f.png",
    "issueNumber": 710
```

2021-09-14 12:05 UTC, Omkar0114 commented
I updated the Image URL of the profile

2021-09-14 12:11 UTC, closed without merging

2021-09-14 15:22 UTC, CodingSpecies reviewed
Thank you for doing the readme @Omkar0114 , I think just the formatting of the tabs like @schmelto said. Thanks.