add devesh-anand
EddieHubCommunity/awesome-github-profiles pull request #716
Opened 2021-09-14 16:15 UTC by devesh-anand

resolve #715

2021-09-14 17:58 UTC, Panquesito7 commented on data.json
> +
Please remove this line.
```suggestion
```

2021-09-14 17:58 UTC, Panquesito7 commented on data.json
> +
Same here.
```suggestion
```

2021-09-14 18:39 UTC, schmelto requested changes
Please see @Panquesito7 comments above

2021-09-15 10:00 UTC, schmelto approved these changes

2021-09-15 10:01 UTC, merged