add shreyaansjain06
EddieHubCommunity/awesome-github-profiles pull request #727
Opened 2021-09-20 09:50 UTC by shreyaansjain06

Resolves #726

2021-09-20 09:52 UTC, schmelto requested changes
Please add yourself at the end of the data.json.
See bullet point 3 [here](https://github.com/EddieHubCommunity/awesome-github-profiles#how-can-i-add-my-github-profile)

2021-09-20 09:56 UTC, shreyaansjain06 commented
ok

2021-09-20 15:42 UTC, Panquesito7 commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/86606251/133983008-13e73a8d-fb2b-4592-98b1-7f1cfbbcbb69.png",
I would recommend more of an image like this.

![image](https://user-images.githubusercontent.com/51391473/134031514-b0bbff29-3974-4f05-a2c6-a5c163e90216.png)

```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/51391473/134031514-b0bbff29-3974-4f05-a2c6-a5c163e90216.png",
```

2021-09-21 07:21 UTC, schmelto approved these changes

2021-09-21 14:14 UTC, merged