Update data.json
EddieHubCommunity/awesome-github-profiles pull request #731
Opened 2021-09-25 13:09 UTC by rehanpunjwani

Resolve #730

2021-09-25 14:03 UTC, deephunt3r approved these changes
LGTM 🚀 Thanks for your contribution 🎉

2021-09-25 15:50 UTC, schmelto approved these changes

2021-09-26 02:20 UTC, Panquesito7 requested changes

2021-09-26 02:20 UTC, Panquesito7 commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/49568477/134772561-9e56321a-e6fa-4e85-89a7-52adcb447ffd.png",
I would recommend more of an image like this.

![image](https://user-images.githubusercontent.com/51391473/134791010-7e18ffeb-f5f1-4b0f-ac41-4c4bc9006485.png)

```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/51391473/134791010-7e18ffeb-f5f1-4b0f-ac41-4c4bc9006485.png",
```

2021-09-26 14:50 UTC, Panquesito7 requested changes
Please resolve the [**merge conflicts**](https://github.com/EddieHubCommunity/awesome-github-profiles/pull/731/conflicts).

2021-09-26 22:17 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-09-26 22:18 UTC, merged