Add aniket-24
EddieHubCommunity/awesome-github-profiles pull request #732
Opened 2021-09-25 20:48 UTC by aniket-24

resolve #732

2021-09-25 20:49 UTC, aniket-24 commented
@Panquesito7 please review and merge this!

2021-09-26 00:44 UTC, deephunt3r commented on data.json
>    }
```suggestion
  }, 
```

2021-09-26 00:46 UTC, deephunt3r commented on data.json
>    }
Could you please make the required changes

2021-09-26 01:58 UTC, Panquesito7 requested changes

2021-09-26 01:58 UTC, Panquesito7 commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/76562459/133885424-2f4af13d-239f-4e59-a2e7-e6324e275e55.png",
I would recommend more of an image like this.
![image](https://user-images.githubusercontent.com/51391473/134790539-719a671c-65d8-42b4-8ea7-3c2cf6f760bf.png)

```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/51391473/134790539-719a671c-65d8-42b4-8ea7-3c2cf6f760bf.png",
```

2021-09-26 05:58 UTC, aniket-24 reviewed
Now is it okay ? @deephunt3r

2021-09-26 06:05 UTC, schmelto approved these changes

2021-09-26 06:23 UTC, aniket-24 commented
@schmelto @Panquesito7 what all changes are required to merge this PR

2021-09-26 08:33 UTC, aniket-24 commented
Now, is it okay? @Panquesito7

2021-09-26 14:38 UTC, Panquesito7 commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/76562459/134800047-8d5db274-3916-486f-9652-ea1e867cbd9d.png",
I would recommend more of an image like this.

![image](https://user-images.githubusercontent.com/51391473/134812399-6a005576-3b24-46a6-b9bc-7798f79e5bf1.png)

```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/51391473/134812399-6a005576-3b24-46a6-b9bc-7798f79e5bf1.png",
```

2021-09-26 15:00 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍
Thanks for reviewing this pull request, folks! 🙂

2021-09-26 15:00 UTC, merged