Update data.json
EddieHubCommunity/awesome-github-profiles pull request #746
Opened 2021-10-02 04:06 UTC by Gur-jot

please add my Readme File also

2021-10-02 07:09 UTC, schmelto requested changes
Please add yourself at the end of the data.json file

2021-10-02 08:05 UTC, CodingSpecies requested changes
> 
> 
> please add my Readme File also

@Gur-jot your readme will be added, as you gave the image url to it. 
Also, see the changes @schmelto reviewed.

2021-10-02 09:00 UTC, Gur-jot commented
@schmelto I just add myself at the end I hope it is right now

2021-10-02 09:02 UTC, schmelto requested changes

2021-10-02 09:02 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-10-02 09:02 UTC, schmelto commented on data.json
> +
```suggestion
```

2021-10-02 09:02 UTC, schmelto commented on data.json
>    }
```suggestion
  },
```

2021-10-03 04:36 UTC, Panquesito7 commented on data.json
> +    "githubUsername": "gur-jot",
```suggestion
    "githubUsername": "Gur-jot",
```

2021-10-03 15:01 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-10-03 15:02 UTC, merged