add AaquibAli
EddieHubCommunity/awesome-github-profiles pull request #748
Opened 2021-10-02 08:06 UTC by AaquibAli

resolve #747

2021-10-02 09:00 UTC, schmelto requested changes

2021-10-02 09:00 UTC, schmelto commented on data.json
>    }
```suggestion
  },
```

2021-10-02 09:00 UTC, schmelto commented on data.json
> +    "imageUrl": "![aaquib](https://user-images.githubusercontent.com/84700316/135708541-936038fd-97c2-4fc0-a51d-7d6a5b96dbf1.png",
```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/84700316/135708541-936038fd-97c2-4fc0-a51d-7d6a5b96dbf1.png",
```

2021-10-02 09:11 UTC, AaquibAli commented
i change the review. please have a look @schmelto

2021-10-02 09:18 UTC, schmelto approved these changes

2021-10-02 09:20 UTC, merged

2021-10-02 09:20 UTC, schmelto commented
**Thanks for your contribution** 🚀 

I hope you enjoyed the process and we see us in some other PRs again.

2021-10-02 09:21 UTC, AaquibAli commented
Thanks for merging this PR

On Sat, Oct 2, 2021, 2:50 PM Tom Schmelzer ***@***.***> wrote:

> *Thanks for your contribution* 🚀
>
> I hope you enjoyed the process and we see us in some other PRs again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/748#issuecomment-932720933>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUGGZHAUN32TRWQ2EIFKN53UE3FGVANCNFSM5FGD2YEQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-05-15 01:39 UTC, takasurazeem commented
Profile no longer exists