Add ektaarora16
EddieHubCommunity/awesome-github-profiles pull request #750
Opened 2021-10-02 08:24 UTC by ektaarora16

resolved #749

2021-10-02 08:27 UTC, CodingSpecies approved these changes
LGTM, thank you for contributing @ektaarora16 !

2021-10-02 08:59 UTC, AaquibAli approved these changes

2021-10-02 09:00 UTC, schmelto requested changes

2021-10-02 09:00 UTC, schmelto commented on data.json
>    }
```suggestion
  },
```

2021-10-02 09:03 UTC, KukretiShubham approved these changes
after changes by Tom.
LGTM

2021-10-02 10:15 UTC, ektaarora16 commented
changes done. Please revive it

2021-10-02 10:16 UTC, ektaarora16 commented
Please review @schmelto

2021-10-02 10:16 UTC, KukretiShubham approved these changes
LGTM 🚀

2021-10-02 10:19 UTC, KukretiShubham commented
Hey, there are merge conflict. Hope maintainers will resolve. And @ektaarora16 you can also avoid merge conflict by fetching the upstream on your forked repo.

2021-10-03 04:41 UTC, Panquesito7 requested changes
Please resolve the [**merge conflicts**](https://github.com/EddieHubCommunity/awesome-github-profiles/pull/750/conflicts). If you need any help, don't hesitate to ask for help here or in our [**Discord server**](http://discord.eddiehub.org). 🙂

2021-10-03 04:41 UTC, Panquesito7 commented on data.json
> +    "imageUrl": "https://user-images.githubusercontent.com/90129737/135709011-e377fce0-d0b9-46d5-8eff-f2edec70e8fa.png",
I would recommend more of an image like this.

![image](https://user-images.githubusercontent.com/51391473/135740246-b0be6db0-160a-43d8-819d-0ad3c190619c.png)

```suggestion
    "imageUrl": "https://user-images.githubusercontent.com/51391473/135740246-b0be6db0-160a-43d8-819d-0ad3c190619c.png",
```

2021-10-03 09:00 UTC, ektaarora16 commented
Resolved conflict. Please revive it.

2021-10-03 09:03 UTC, KukretiShubham approved these changes

2021-10-03 15:00 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-10-03 15:01 UTC, merged