fix: Add Chayan-11 to the list
EddieHubCommunity/awesome-github-profiles pull request #778
Opened 2021-10-16 13:53 UTC by Chayan-11

Resolve #777

2021-10-16 15:02 UTC, krishguptadev approved these changes

2021-10-17 00:21 UTC, Panquesito7 requested changes

2021-10-17 00:21 UTC, Panquesito7 commented on data.json
> +  "issueNumber": 777
```suggestion
    "name": "Chayan Debbarma",
    "githubUsername": "Chayan-11",
    "imageUrl": "https://user-images.githubusercontent.com/76246106/137589642-7e33d835-d02d-4f20-9fec-85c35554c2a2.png",
    "issueNumber": 777
```

2021-10-17 15:52 UTC, helper-uttam approved these changes

2021-10-17 16:25 UTC, Panquesito7 commented on data.json
> +  "issueNumber": 777
```suggestion
    "name": "Chayan Debbarma",
    "githubUsername": "Chayan-11",
    "imageUrl": "https://user-images.githubusercontent.com/76246106/137589642-7e33d835-d02d-4f20-9fec-85c35554c2a2.png",
    "issueNumber": 777
```

2021-10-17 16:27 UTC, merged

2021-10-18 01:59 UTC, krishguptadev reviewed
LGTM!