Profile issue commit
EddieHubCommunity/awesome-github-profiles pull request #816
Opened 2021-10-31 08:57 UTC by UltimateBrains

2021-10-31 09:12 UTC, AvidCoder101 requested changes
@UltimateBrains the issue number doesn't seem to be correct and seems to be someone else's. Could you please open a new issue with you image url in the description and then link the issue number to the PR? Please tell us if you need help. Thanks (:

2021-10-31 09:12 UTC, CodingSpecies requested changes
@UltimateBrains I don't think you have opened an issue.
- Open an issue, and call it `add UltimateBrains`.
- Paster your image in: use this `![profile](https://user-images.githubusercontent.com/20683046/139575119-4c44ca4f-9a7d-4aa9-9d40-b9b930707353.png)` .
- Open the issue.
- Get the issue number, and change this to the correct issue num.

If you need any more help, feel free to ask.

2021-10-31 10:15 UTC, UltimateBrains commented
Okay,Let me check

2021-10-31 10:28 UTC, CodingSpecies reviewed
Thank you for adding the issue, and the number.

2021-10-31 10:29 UTC, CodingSpecies requested changes

2021-10-31 10:29 UTC, CodingSpecies commented on data.json
> +   {
Please can you format line `1550`, so the brace is in line? @UltimateBrains 
After that, it should be good.

2021-10-31 11:00 UTC, CodingSpecies approved these changes
Thank you @UltimateBrains LGTM.

2021-10-31 14:41 UTC, Panquesito7 commented on data.json
> +    "name": "Amitkumar",
Shouldn't your name be `Amit Kumar`?
```suggestion
    "name": "Amit Kumar",
```

2021-11-20 15:19 UTC, shreyaansjain06 requested changes
Please do changes suggested by @Panquesito7

2021-11-20 15:26 UTC, krishguptadev requested changes
Please check @Panquesito7's comments

2021-11-20 15:27 UTC, krishguptadev reviewed
## Merge Conflict

Thank you for your contribution. Your pull request currently has conflicting changes with our `main` branch. In order to review this pull request, we will need those conflicts to be resolved.

We recommend doing this with the `git rebase` command. If you are unsure of how to fix this, let us know and we would be happy to assist you.

2021-11-21 01:35 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-11-21 01:35 UTC, merged

2021-11-21 03:25 UTC, krishguptadev reviewed
LGTM!