add ckvignesh
EddieHubCommunity/awesome-github-profiles pull request #828
Opened 2021-11-03 15:37 UTC by ckvignesh

resolve #825

2021-11-03 15:39 UTC, ckvignesh commented
Hi @eddiejaoude, can you please help with this?

2021-11-03 15:44 UTC, schmelto commented
Closing in favor of #826

2021-11-03 15:45 UTC, schmelto requested changes

2021-11-03 15:45 UTC, schmelto commented on data.json
> +  {
```suggestion
  },
  {
```

2021-11-03 15:45 UTC, schmelto commented on data.json
>  }
```suggestion
  }
```

2021-11-03 16:23 UTC, ckvignesh commented on data.json
> +  {
Done, @schmelto ...

2021-11-03 16:51 UTC, schmelto approved these changes

2021-11-03 16:54 UTC, merged

2021-11-03 17:29 UTC, Panquesito7 reviewed
LGTM! 🚀

2021-11-04 01:55 UTC, krishguptadev reviewed
LGTM!

2021-11-04 02:20 UTC, ckvignesh commented
> LGTM! rocket

Thank you!

2021-11-04 02:20 UTC, ckvignesh commented
> LGTM!

Thank you!