fix: Add RayyanRNKJ
EddieHubCommunity/awesome-github-profiles pull request #838
Opened 2021-11-14 20:00 UTC by RayyanRNKJ

resolve #837

2021-11-14 20:11 UTC, Panquesito7 commented on data.json
> +  "issueNumber": 837
```suggestion
      "name": "Rayyan Rasheed",
      "githubUsername": "RayyanRNKJ",
      "imageUrl": "https://user-images.githubusercontent.com/64679235/141696204-3084d6cf-49d0-452a-979e-35a58b89b4dc.png",
      "issueNumber": 837
```

2021-11-14 20:11 UTC, Panquesito7 commented on data.json
> +  },
```suggestion
},
```

2021-11-15 04:08 UTC, Panquesito7 requested changes
Please see https://github.com/EddieHubCommunity/awesome-github-profiles/pull/838/files#r748902485. 😄

2021-11-15 06:13 UTC, schmelto commented on data.json
> +  {
```suggestion
  },
  {
```

2021-11-15 08:34 UTC, closed without merging