add Achilles8055
EddieHubCommunity/awesome-github-profiles pull request #843
Opened 2021-11-15 12:40 UTC by Achilles8055

resolve #842

2021-11-15 13:10 UTC, krishguptadev approved these changes

2021-11-15 17:10 UTC, Panquesito7 commented on data.json
> + },
```suggestion
},
```

2021-11-15 17:34 UTC, shreyaansjain06 requested changes
Please fix what @Panquesito7 suggested

2021-11-16 01:43 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍
By the way, I liked your profile 🎉 it's awesome.

2021-11-16 01:49 UTC, merged

2021-11-16 02:12 UTC, Achilles8055 commented
Thanks,  David Leal for the compliment. It means a lot.  Looking forward to
learn and contribute more  😊😊

On Tue, Nov 16, 2021 at 7:19 AM David Leal ***@***.***> wrote:

> Merged #843
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/843>
> into main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/awesome-github-profiles/pull/843#event-5621872353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU75HDVWUDTSW3FCM6PEYR3UMG2B5ANCNFSM5IBS33JA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>