Updated <title>
EddieHubCommunity/awesome-github-profiles pull request #921
Opened 2021-12-17 17:27 UTC by adityapalve

2021-12-17 18:54 UTC, Panquesito7 requested changes

2021-12-17 18:54 UTC, Panquesito7 commented on pages/index.js
> +        <title>Awesome GitHub profile</title>
```suggestion
        <title>Awesome GitHub Profiles</title>
```

2021-12-17 21:58 UTC, schmelto approved these changes

2021-12-17 22:00 UTC, Panquesito7 approved these changes

2021-12-18 01:10 UTC, eddiejaoude approved these changes
Great! Thank you 👍

2021-12-18 01:11 UTC, merged