add SamirPaul1
EddieHubCommunity/awesome-github-profiles pull request #937
Opened 2021-12-25 20:00 UTC by SamirPaul1

resolves #`936`

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2021-12-26 02:12 UTC, Panquesito7 commented on profiles/SamirPaul1.json
> +  "image": "https://raw.githubusercontent.com/SamirPaul1/cv/main/assets/img/SamirPaul1-Overview.png",
I recommend more of an image like this.

![image](https://user-images.githubusercontent.com/51391473/147397131-a108815e-874b-455c-ba15-224c954b44ca.png)

```suggestion
  "image": "https://user-images.githubusercontent.com/51391473/147397131-a108815e-874b-455c-ba15-224c954b44ca.png",
```

2021-12-26 02:12 UTC, Panquesito7 commented on profiles/SamirPaul1.json
> +  "name": "SAMIR PAUL",
```suggestion
  "name": "Samir Paul",
```

2022-01-31 14:46 UTC, krshdev requested changes
Hey @SamirPaul1 👋 Do you need any help with this? Please do the changes requested above by @Panquesito7 🙂

2022-02-02 11:34 UTC, SamirPaul1 commented
Hello @krshdev I have changed the SamirPaul1.json file now you can merge it.

2022-02-02 13:49 UTC, krshdev approved these changes

2022-02-02 14:07 UTC, Panquesito7 approved these changes

2022-02-02 14:11 UTC, merged