fix: add gurjeetsinghvirdee
EddieHubCommunity/awesome-github-profiles pull request #951
Opened 2022-01-01 11:06 UTC by gurjeetsinghvirdee

resolves #950 

## Checklist for profile addition

- [ ] Name the PR `fix: add <your-username>`.
- [ ] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [ ] You've linked the PR to the correct issue.

---

## Other additions/changes

- [ ] Changes made in this PR are mentioned below
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.
- [ ] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)

## This PR adds/fixes

## Notes

2022-01-01 11:15 UTC, syedsohan requested changes

2022-01-01 11:15 UTC, syedsohan commented on profiles/GurjeetSinghVirdee.json
> +}
```suggestion
}

```

Add newline after line number `6`.

2022-01-01 11:46 UTC, syedsohan approved these changes

2022-01-01 13:40 UTC, krishguptadev commented on profiles/GurjeetSinghVirdee.json
> +  "image": "https://user-images.githubusercontent.com/73753957/147848925-4655ce63-2950-4deb-9931-e8140909bf74.png",
I prefer an image more like =>

![image](https://user-images.githubusercontent.com/91655303/147851908-077a0481-2330-4853-995a-b0c041a4682b.png)

```suggestion
  "image": "https://user-images.githubusercontent.com/91655303/147851903-7af25096-b607-42a2-bbfb-e7e77c53ecb6.png",
```

2022-01-01 15:43 UTC, krishguptadev approved these changes

2022-01-02 04:11 UTC, Panquesito7 commented on profiles/GurjeetSinghVirdee.json
> +  "image": "https://user-images.githubusercontent.com/91655303/147851903-7af25096-b607-42a2-bbfb-e7e77c53ecb6.png",
```suggestion
  "image": "https://user-images.githubusercontent.com/73753957/147848925-4655ce63-2950-4deb-9931-e8140909bf74.png",
```

2022-01-03 05:04 UTC, Panquesito7 commented on profiles/GurjeetSinghVirdee.json
> +  "image": "https://user-images.githubusercontent.com/73753957/147848925-4655ce63-2950-4deb-9931-e8140909bf74.png",
Sorry if I reverted this, Krish, didn't see this properly. 😅
```suggestion
  "image": "https://user-images.githubusercontent.com/91655303/147851903-7af25096-b607-42a2-bbfb-e7e77c53ecb6.png",
```

2022-01-03 05:06 UTC, Panquesito7 approved these changes

2022-01-03 05:06 UTC, merged