fix: binitrajshah7.json
EddieHubCommunity/awesome-github-profiles pull request #999
Opened 2022-01-30 18:34 UTC by binitrajshah7

resolves #998 

## Checklist for profile addition

- [x] Name the PR `fix: add <your-username>`.
- [x] You've added file named `your-username.json` in the [profiles](https://github.com/EddieHubCommunity/awesome-github-profiles/tree/main/profiles) directory.
- [x] You've linked the PR to the correct issue.

---

## Other additions/changes

- [x] Changes made in this PR are mentioned below
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.
- [x] I've read the [contributing guidelines](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/CONTRIBUTING.md)
## This PR adds/fixes

- Adds New GitHub Profile to the Repository

## Notes

- I have mistakenly given the wrong issueId in my profile binitrajshah7.json file and I'm not able to edit it as it is not in the main branch sooner the file gets merged to the main branch I would edit it and commit the necessary changes. 
- Original issueID : 998
- Misktaken issueID in .json file : 999

2022-01-30 21:51 UTC, Panquesito7 requested changes

2022-01-30 21:51 UTC, Panquesito7 commented on profiles/binitrajshah7.json
> +  "issueId": 999,
Wrong issue ID.
```suggestion
  "issueId": 998,
```

2022-01-31 14:33 UTC, Panquesito7 approved these changes

2022-01-31 14:45 UTC, krshdev approved these changes

2022-01-31 14:47 UTC, merged